### ISSUE TITLE
URGENT: Survey question about What best describes your sexual orientation? 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#100]
![Screen Shot 2020-05-09 at 12 51 34 PM](https://user-images.githubusercontent.com/64874011/81483600-370f0380-91f4-11ea-836e-6fa5e23ea817.png)

Currently this question is in Survey 3 before the Do you smoke question. 
It should be the last question on Survey 4 instead. 

Thanks

**Comment by conundrumgirl** [comment]
done
