### ISSUE TITLE
Surveys: "Responses required above" text is faded..please make full opacity

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#116]
![Screen Shot 2020-05-11 at 4 58 34 PM](https://user-images.githubusercontent.com/64874011/81623551-ab8aa380-93a8-11ea-8822-3d4d362c4d21.png)

Match "responses required above" with "is a required field" 
Can we make into "Open sans" font instead of Source serif

**Comment by conundrumgirl** [comment]
done
