### ISSUE TITLE
Survey 3: Fever followup question about temperature: should be in Fahrenheit

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#118]
![Screen Shot 2020-05-11 at 5 05 45 PM](https://user-images.githubusercontent.com/64874011/81623906-a7ab5100-93a9-11ea-95d4-33cf59bbb4da.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-11 at 5 06 34 PM](https://user-images.githubusercontent.com/64874011/81623953-c6114c80-93a9-11ea-92be-4250585f8cf0.png)

**Comment by conundrumgirl** [comment]
done
