### ISSUE TITLE
URGENT: exiting consent process

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#123]
![Screen Shot 2020-05-11 at 6 02 09 PM](https://user-images.githubusercontent.com/64874011/81626784-8c444400-93b1-11ea-9062-75153d5a1555.png)

If user exits with the "x" button on the Consent screen, 
they get confirmation dialog with text string 

"Are you sure you want to leave the consent process?"
[Yes]
[No, take me back]

See image.

If they hit Yes , they're still logged in but they won't see dashboard only error statement that calls out that they need to start their consent.

Error statement: (see image) 

"You will need to complete the consent process before you can join the study."
[Start consent]

All text has been verified by Vanessa

**Comment by jay-hodgson** [comment]
Confirmation dialog was only implemented to be shown when clicking the Disagree button on the final consent screen.
Current plan (fastest, but not ideal) is to change the confirmation dialog content based on the design, and add the new alert to the home screen (shown if user cancels the consent process, which allow the user to easily go back to the consent process).

**Comment by jay-hodgson** [comment]
Also change global alert message to be a centered component (note: not text aligned center).
And scroll to the top of the window when the route changes, or a page is changed in the consent process.

**Comment by jay-hodgson** [comment]
After talking to Lynn, I need to hook up the cancel dialog to the floating toolbars, and remove the Disagree button.
