### ISSUE TITLE
URGENT: Survey 3, Q4:  missing a response

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#125]
Need to add additional first response as:

"My COVID-19 was managed at home" 

![Screen Shot 2020-05-11 at 6 22 07 PM](https://user-images.githubusercontent.com/64874011/81628001-53599e80-93b4-11ea-9eca-766cbc7a5853.png)

**Comment by conundrumgirl** [comment]
done
