### ISSUE TITLE
Survey 3: Question 4b. Other Text string change

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#126]
![Screen Shot 2020-05-11 at 6 26 14 PM](https://user-images.githubusercontent.com/64874011/81628221-e7c40100-93b4-11ea-99f5-0d0965cb851b.png)

Text string for selection should be "Other Complications" followed by "Please specify:" see image 

![Screen Shot 2020-05-11 at 6 29 16 PM](https://user-images.githubusercontent.com/64874011/81628358-53a66980-93b5-11ea-9217-1c26f5e3fa45.png)

**Comment by conundrumgirl** [comment]
done
