### ISSUE TITLE
Survey 3: labeling of Q11 should be Q5. 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#127]
![Screen Shot 2020-05-11 at 6 29 34 PM](https://user-images.githubusercontent.com/64874011/81628378-5ef99500-93b5-11ea-8f1b-4e4c44807e74.png)

Because the survey was rearranged, the labeling of the questions need to be updated: 

labeling of question number 11 should be : 5. 
labeling of question number 12 should be : 6
labeling of question number 5-10 should be 7-12.

**Comment by conundrumgirl** [comment]
done
