### ISSUE TITLE
low priority: Survey 3: Q4a. label and text string edits

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#128]
![Screen Shot 2020-05-11 at 6 39 08 PM](https://user-images.githubusercontent.com/64874011/81628880-b3e9db00-93b6-11ea-900c-1f0b863bea32.png)

Question should be numbered "6a."
(select all that apply) should be "(check all that apply)"

**Comment by conundrumgirl** [comment]
done
