### ISSUE TITLE
URGENT: Survey 3: Do you smoke question and subsequent question

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#129]
Currently subsequent question drops under "Prefer not to answer" 

![Screen Shot 2020-05-11 at 6 45 13 PM](https://user-images.githubusercontent.com/64874011/81629246-8d786f80-93b7-11ea-9e4f-d1f4cb231a2c.png)

Should spin off as secondary question if user selects " I smoke every day." 
**Also please make sure "Prefer Not To Answer" is always labeled as " Prefer not to answer" consistently. 

![Screen Shot 2020-05-11 at 6 45 04 PM](https://user-images.githubusercontent.com/64874011/81629238-894c5200-93b7-11ea-8454-40ae0b54efe5.png)

**Comment by conundrumgirl** [comment]
done
