### ISSUE TITLE
URGENT: Contact Information page updates

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#130]
![Screen Shot 2020-05-11 at 7 08 54 PM](https://user-images.githubusercontent.com/64874011/81630577-dd0c6a80-93ba-11ea-8536-12b2ccd50df2.png)

Feels awkward to ask typical Contact information in forms of questions. 
Help user get through this quicker: please reference image 

Missing "Contact Information" header
Text string update under Date of birth
Address form field missing second address row. 

Please provide Hint texts consistently on the form fields.

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy "Please provide Hint texts consistently on the form fields." - it it is a requirement for all the survey forms please add it as a different issues and provide the copy

**Comment by conundrumgirl** [comment]
#139 #
