### ISSUE TITLE
Create way to label test data

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#145]
Prior to launch, all data generated by the web app should  be labeled test data. Even after launch, would be good to have a Synapse style "alpha mode" for testing unreleased new features, this mode should also label the data as test.

**Comment by jay-hodgson** [comment]
@alxdarksage : How should we label test data?  Maybe a user attribute (web app might mark if url contains staging or is localhost)?  @conundrumgirl : Ideas?

**Comment by conundrumgirl** [comment]
I recall @alxdarksage has a 'test_user' usergroup that we can assign to the user during registration.
I like your idea about just testing against location, @jay-hodgson

**Comment by jay-hodgson** [comment]
From @alxdarksage : 
> add "test_user" to the "dataGroups" property of the sign up object
> "dataGroups": ["test_user"]
