### ISSUE TITLE
Pending Logo treatment: Welcome Consent screen

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#147]
1. Currently the welcome screen on iPhone, when user drags navigation peeks out? 

![IMG_134E7F851E59-1](https://user-images.githubusercontent.com/64874011/81748745-375f0700-945f-11ea-98e1-c2b6df78ba82.jpeg)

2. Logo needs to be added (TBD)
3. New Body text string update--->

Before you decide to join the study, let's learn more about COVID Recovery Corps.

The next screens will tell you about the purpose of the study, what we will ask you to do, the benefits and risks of participation.

---
4. Add card bg to match updated screens across devices. 
![Screen Shot 2020-05-12 at 2 47 38 PM](https://user-images.githubusercontent.com/64874011/81748914-87d66480-945f-11ea-8b88-7ba5954d2d64.png)

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy  - I am closing this. We can open another issue for logo
