### ISSUE TITLE
URGENT!!!!! Sign up flow updates

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#154]
After a person is eligible, we focus on gathering Email first and provide option to sign up via phone if they don't have an email. 

1. Getting started screen: 
Getting Started 

To access the consent and surveys, you will need to create an account.  

You will use your email to log into your account in the future.

[blue line]

[Email input field] 

[Create account]

[link : "I don’t have an email account" in same blue and underlined]

2. Magic link screen:  
If they sign up via email we surface "we just sent link to: 

2b. If no email screen:  

Don't have email? 

At this time, we are only able to invite participants to lab draws with an email account. 

We are working on this issue. We hope to support scheduling appointments with your phone number in the near future. 

You can still provide important information to our researchers by filling out surveys.

[Phone input field]

[Create account]

3. Enter code screen

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-12 at 7 26 46 PM](https://user-images.githubusercontent.com/64874011/81764483-89ffe980-9486-11ea-8d44-2c46d6598926.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-12 at 7 27 54 PM](https://user-images.githubusercontent.com/64874011/81764552-af8cf300-9486-11ea-9aa6-88b14bb97385.png)

**Comment by conundrumgirl** [comment]
#162
