### ISSUE TITLE
Update html styles on email login 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#155]
![Screen Shot 2020-06-02 at 3 36 39 PM](https://user-images.githubusercontent.com/64874011/83576545-dc14b780-a4e6-11ea-9d27-6d1d8a8e4181.png)

Subject line: COVID Recovery Corps - Log into Account

[CRC logo] on top left

"Hello!"

"Please click the link below to access your account."

[Log in]

If you have any questions or need assistance, you can call 212-305-5700 or email COVIDRecoveryCorps@cumc.columbia.edu

[Columbia and Sage logo] 

[CRClogo&OrgLogos.zip](https://github.com/Sage-Bionetworks/covidrecoverycorps/files/4720029/CRClogo.OrgLogos.zip)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![logo_C S](https://user-images.githubusercontent.com/64874011/81761203-2ffb2600-947e-11ea-93a9-e829efd7e9ef.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![logo_C S](https://user-images.githubusercontent.com/64874011/81891217-ba19bc00-955c-11ea-8b69-8da5ca1429a4.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![logo_emailtemplate](https://user-images.githubusercontent.com/64874011/82127363-ca51b700-9767-11ea-9227-c7abc9d4c549.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
I've updated with the email template with new logo. Since we are only having one email template regardless of when they join or relogin - we thought it was better to have a generic Hello. Rather than "let's get started."

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![logo_CRC](https://user-images.githubusercontent.com/64874011/87698279-1a3d0200-c748-11ea-993b-f751d3d29584.png)
![logo_CUSage](https://user-images.githubusercontent.com/64874011/87698281-1ad59880-c748-11ea-836c-f84f4871aee9.png)

**Comment by alxdarksage** [comment]
Updated.
