### ISSUE TITLE
low priority  Login link expiration notification page

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#156]
Currently if user signs up and an hour passes and they don't open email we send them to log in page which is confusing since technically they were joining so they can't officially log in. 

Or if they're signed in and time passes, they're kicked out without a message. 

![icon_expired](https://user-images.githubusercontent.com/64874011/82155781-25e57880-982c-11ea-8114-dbaf33758001.png)

Text: "Sorry, your session has expired." (Opens Sans, 16pts, regular, 2.6 rems)

[Log in]
[Join us]

![Screen Shot 2020-05-17 at 10 48 25 AM](https://user-images.githubusercontent.com/64874011/82155752-f0408f80-982b-11ea-82dc-00365d0c2869.png)

**Comment by conundrumgirl** [comment]
won't fix
