### ISSUE TITLE
URGENT: bg #F5f5f5 card across components

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#157]
To reduce floating text, There is a grey card that sits behind the following UI elements with hex value of #F5f5f5 Please see redlines attached
![Screen Shot 2020-05-12 at 7 18 22 PM](https://user-images.githubusercontent.com/64874011/81763983-596b8000-9485-11ea-82f5-0d1f1d2d370f.png)
![Screen Shot 2020-05-12 at 7 18 34 PM](https://user-images.githubusercontent.com/64874011/81763994-60928e00-9485-11ea-9a57-36023c7c6914.png)

+ Eligibility
+ Geting started
+ Log in 
+ Expiration page
+ Consent
+ HIPAA 
+ Surveys
+ Account Settings

**Comment by conundrumgirl** [comment]
@ #163
