### ISSUE TITLE
URGENT: user mistypes wrong email address

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#158]
Login from hamburger should force "refresh" if user mistypes address and attempts to login again. 

Currently if user clicks on login - it stays on same page.

![Screen Shot 2020-05-12 at 7 37 00 PM](https://user-images.githubusercontent.com/64874011/81765199-0646fc80-9488-11ea-9ab3-24ab2af0c0a4.png)

**Comment by conundrumgirl** [comment]
we just need to make sure that login forces navigation even when they are on the login page

**Comment by conundrumgirl** [comment]
#160
