### ISSUE TITLE
URGENT!!!!  pregnancy questions branching isn't matching figma flow

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#165]
![image](https://user-images.githubusercontent.com/64874011/81876558-d820f580-9537-11ea-9e7b-3d84bfcbf62b.png)

1. If you're not pregnant you still get the other pregnant related questions
2. Cant seem to submit the responses even though all answers are inputted..

**Comment by conundrumgirl** [comment]
https://github.com/Sage-Bionetworks/covidrecoverycorps/pull/169
