### ISSUE TITLE
!!! Consent Icons _ please see notes below

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#166]
Redlines for how to update text string and apply icons across consent form: 
![Screen Shot 2020-05-14 at 12 51 48 PM](https://user-images.githubusercontent.com/64874011/81979365-ae240d80-95e1-11ea-997f-a2a8fb46008c.png)

![Screen Shot 2020-05-14 at 12 50 40 PM](https://user-images.githubusercontent.com/64874011/81979270-85037d00-95e1-11ea-9b8e-ff3e8b6d1016.png)

![1 About the study](https://user-images.githubusercontent.com/64874011/81979529-f93e2080-95e1-11ea-8bc0-a91bb33d14a1.png)
![3  what will I be asked todo](https://user-images.githubusercontent.com/64874011/81979530-f9d6b700-95e1-11ea-9da0-156340d6e0aa.png)
![4  What are the benefits_](https://user-images.githubusercontent.com/64874011/81979532-f9d6b700-95e1-11ea-86ee-ab1c59dcd72d.png)
![5 Whataretherisks](https://user-images.githubusercontent.com/64874011/81979534-f9d6b700-95e1-11ea-9ddb-9b178e8fbdd1.png)
![7  DataSamples](https://user-images.githubusercontent.com/64874011/81979536-fa6f4d80-95e1-11ea-9914-9f9a02bcc7f3.png)
![8  Sharing your data](https://user-images.githubusercontent.com/64874011/81979537-fa6f4d80-95e1-11ea-9f53-6a7d37f5dea8.png)
![10  Notmedicalcare](https://user-images.githubusercontent.com/64874011/81979538-fa6f4d80-95e1-11ea-87a5-7c0f2a0a2518.png)
![11  Leaving the study](https://user-images.githubusercontent.com/64874011/81979539-fb07e400-95e1-11ea-95c8-10f237778caa.png)
![12  Things you should consider before you say yes](https://user-images.githubusercontent.com/64874011/81979541-fb07e400-95e1-11ea-99e1-5e93f90e6d1c.png)
![13  How to contact us_](https://user-images.githubusercontent.com/64874011/81979542-fb07e400-95e1-11ea-8a6c-080f73743b51.png)

**Comment by conundrumgirl** [comment]
#176

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Reopening because we are still using Source serif pro for the body... :( 

Header: 
Playfair Display, 24pt, 700 (bold) instead of the current 500 

Body copy: 
Please use Open Sans, 16pt, regular, 2.6 rem 

Page numbers: to match survey updates:  Playfair Display, 14pts, 700 (bold),
 #2a2a2a
