### ISSUE TITLE
!!! HIPAA icons and style updates

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#167]
Notice that the EHR consent experience no longer has 11 screens but 10 in total. Overview was redundant to the start HIPAA screen so was removed.

![Screen Shot 2020-05-14 at 1 37 01 PM](https://user-images.githubusercontent.com/64874011/81983294-ff370000-95e7-11ea-8bc2-49682a5d648e.png)

!!! 
![1  What is an EHR_](https://user-images.githubusercontent.com/64874011/81983995-0d395080-95e9-11ea-8acb-10a4d7df8191.png)
![2  What data is in my EHR_](https://user-images.githubusercontent.com/64874011/81983996-0dd1e700-95e9-11ea-95f8-2c785edca557.png)
![3  Are there sensitive data in my EHR_](https://user-images.githubusercontent.com/64874011/81983997-0e6a7d80-95e9-11ea-95ea-7e92b499a2f0.png)
![4  What exactly will you access in my EHR_](https://user-images.githubusercontent.com/64874011/81983998-0e6a7d80-95e9-11ea-886c-287af0ea2f7e.png)
![5  Why do you want access to my EHR_](https://user-images.githubusercontent.com/64874011/81984000-0e6a7d80-95e9-11ea-8549-78a936ce62bd.png)
![6  Who will be sending you my EHR_](https://user-images.githubusercontent.com/64874011/81984004-0f031400-95e9-11ea-9e40-eb8b70235474.png)
![7  Who will be getting access to my EHR_](https://user-images.githubusercontent.com/64874011/81984006-0f031400-95e9-11ea-8c38-4e8a381bd238.png)
![8  What if I don’t want to give access to my EHR_ What if I change my mind_](https://user-images.githubusercontent.com/64874011/81984007-0f031400-95e9-11ea-9178-8cc26f6a0d53.png)
![9  When will my consent expire_](https://user-images.githubusercontent.com/64874011/81984009-0f9baa80-95e9-11ea-8f36-ddf99270c5fc.png)
![10  Who can answer my questions_](https://user-images.githubusercontent.com/64874011/81984011-0f9baa80-95e9-11ea-8187-2a6b5bf341a8.png)

![Screen Shot 2020-05-14 at 1 37 26 PM](https://user-images.githubusercontent.com/64874011/81983323-0eb64900-95e8-11ea-9339-298dbe956b3b.png)

**Comment by conundrumgirl** [comment]
done- opened the new issue #187  for styles

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Reopening because we are still using Source serif pro for the body... :( 

Header: 
Playfair Display, 24pt, 700 (bold) instead of the current 500 

Body copy: 
Please use Open Sans, 16pt, regular, 2.6 rem 

Page numbers: Open Sans, 700 (bold),

**Comment by conundrumgirl** [comment]
Yes i opened a new issue for that. Also need to add paragraph breaks
