### ISSUE TITLE
Body font Open Sans ---> 2.6 rem line height

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#193]
![Screen Shot 2020-05-15 at 4 46 22 PM](https://user-images.githubusercontent.com/64874011/82104399-9fb22080-96cb-11ea-98be-1782cc4b1c7a.png)

Please make the Open Sans 16pts, regular font line height to be 2.6 rem;

**Comment by jay-hodgson** [comment]
I think this has been fixed by another checkin (across site, these are now paragraphs with line-height set to px set in design doc).

**Comment by jay-hodgson** [comment]
<img width="965" alt="Screen Shot 2020-05-18 at 3 29 08 PM" src="https://user-images.githubusercontent.com/1864447/82265650-5b698f00-991c-11ea-8f3e-61ef224dd881.png">
