### ISSUE TITLE
Survey typographic updates to match home page fonts

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#198]
Survey background bar attached below. (same as survey dashboard)

Surveys 1-4 should have the following body of text below the Title label: "Please fill out the following survey questions to the best of your ability. If you do not remember or would not like to answer, please click "Prefer not to answer". 

![Screen Shot 2020-05-15 at 5 56 22 PM](https://user-images.githubusercontent.com/64874011/82106379-654d8100-96d5-11ea-9ae9-24e97e9a49a7.png)

[bg_rectangle_color.svg.zip](https://github.com/Sage-Bionetworks/covidrecoverycorps/files/4637584/bg_rectangle_color.svg.zip)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
This is how it should scale on desktop:

![Screen Shot 2020-05-15 at 5 50 21 PM](https://user-images.githubusercontent.com/64874011/82106235-8d88b000-96d4-11ea-9e40-447f6196a9d4.png)

**Comment by jay-hodgson** [comment]
@conundrumgirl : The way I implemented the home page does not help the rest of the site (these styles are local to each page).  I'd like to map @flylikeabirdfloatlikeabuoy 's font styles to html elements (especially h1-h6 headings and p paragraphs), and apply those to the Intro/Team/FAQs/Contact pages, which has the potential to fix some of these other font issues across the site.

**Comment by conundrumgirl** [comment]
@jay-hodgson - did you have a specific concern re #220? I think I have covered Lynn's concerns. Did I miss something?
