### ISSUE TITLE
Not consenting error statement: match updated font style and error color FC9090 and keep persistent

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#202]
Can we keep this error statement persistent across all pages? 

Right now it's being cleared when you move away from the About page.  This will be helpful when we show them their appointment
![Screen Shot 2020-05-16 at 11 40 37 AM](https://user-images.githubusercontent.com/64874011/82127642-11d94280-976a-11ea-98bd-b4cbecb40f82.png)

**Comment by jay-hodgson** [comment]
Current error has matching error color, and close to font style (better if in <p>).  
<img width="828" alt="Screen Shot 2020-05-19 at 12 18 18 PM" src="https://user-images.githubusercontent.com/1864447/82368907-06388680-99cb-11ea-89a6-7f4dd1c9781a.png">
Query param is cleared on page change, so it does not persist.  Alternative would be to communicate the alert code using some other mechanism (like session storage), but we'll likely run into the opposite problem (sticks around, no longer relevant).  Note that this alert system is currently used for 2 cases (CANCELLED_CONSENT, and WITHDRAWN_FROM_STUDY), but can and will be expanded to other uses.
