### ISSUE TITLE
UI updates to match design direction with new typography

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#204]
Because of the visual design direction, unfortunately, our login screens and other screens look very much out of place and will have to be updated to match. 

![Screen Shot 2020-05-16 at 2 16 38 PM](https://user-images.githubusercontent.com/64874011/82130395-de091780-977f-11ea-86b3-c2a885786bb1.png)

***We are no longer using Source Serif Pro anywhere****

On mobile, it's fine to keep the top margin the same, but for desktop, we need to add more breathing room from the top navigation bar (recommendation is 72pts) because it looks very cramped. 

Mobile margins are fine: 
![Screen Shot 2020-05-16 at 2 18 53 PM](https://user-images.githubusercontent.com/64874011/82130436-2f190b80-9780-11ea-8f42-51f1d8ec416e.png)

Updated UI to match Playfair Display font and layout of landing pages: 
Eligibility  screen:

![Screen Shot 2020-05-16 at 1 56 07 PM](https://user-images.githubusercontent.com/64874011/82130091-004d6600-977d-11ea-995c-c892339eff66.png)

Getting started screen:
![Screen Shot 2020-05-16 at 2 17 24 PM](https://user-images.githubusercontent.com/64874011/82130415-f8db8c00-977f-11ea-9dda-19589d17dc9f.png)

Don't have email? screen:
Updated body text:
At this time, we are only able to invite participants to lab draws with an email account. 

We are working on this issue. We hope to support scheduling appointments with your phone number in the near future. 

You can still join the COVID Recovery Corps and provide important information to our researchers by filling out surveys with your phone number.

 
![Screen Shot 2020-05-16 at 2 10 11 PM](https://user-images.githubusercontent.com/64874011/82130296-f6c4fd80-977e-11ea-8428-5b85f32062a8.png)

Log in screen: 
![Screen Shot 2020-05-16 at 2 15 03 PM](https://user-images.githubusercontent.com/64874011/82130371-a69a6b00-977f-11ea-96da-b38827701937.png)

**Comment by jay-hodgson** [comment]
@flylikeabirdfloatlikeabuoy (@lbradic)

It's the approach. 
 
Design should identify some basic typography types, and name them!  Whatever names you want (f1, f2, f3).  Then point to different elements and refer to the type (with any specific styles that you want overriding the general type).  This would translate well into scss.

The current approach is to name all attributes of all UI elements, which leads to the current website styling (individual items are styled appropriately, but the design was not communicated in a reusable way so we don't see the styles applied across the site!).

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Let me consolidate all the typography across the different pages and give us something...hang tight.

**Comment by jay-hodgson** [comment]
Updated text on the "Don't have email? screen" and set global styles for headings and paragraph (and changed Intro and Team pages to use these html elements instead of specific styles).

**Comment by jay-hodgson** [comment]
I think I've also removed reference to Source Serif Pro across the site.

**Comment by jay-hodgson** [comment]
This single ticket is a conglomerate of 10+ issues.  I've resolved a number of them, but not all.  I'm going to Close this issue, but @flylikeabirdfloatlikeabuoy please open tickets for specific problems (ideally that are of general applicability across the site).
