### ISSUE TITLE
Consent .pdf needs to include consent text : Spanish & English version 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#208]
![Screen Shot 2020-05-16 at 3 19 51 PM](https://user-images.githubusercontent.com/64874011/82131308-b2d6f600-9788-11ea-9cd4-5c4183118330.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@vbarone00   

Please let me know when you have the copy and we can lay it out for this .pdf

**Comment by vbarone00** [comment]
For the HIPAA Authorization email:

Subject: Your HIPAA Authorization form for providing access to your Electronic Health Record

Hi,

For your reference, here's a copy of the HIPAA Authorization form you just signed to allow the COVID Recovery Corps study access to your electronic health record (EHR)

Regards, 

Columbia University and Sage Bionetworks

For general inquiries or to request with your account, please email COVIDRecoveryCorps@cumc.columbia.edu

For consent form email:

Subject: Your Consent Form for participating in the COVID Recovery Corps study
Hi,

For your reference, here's a copy of the consent form you just signed to participate in the COVID Recovery Corps study.

Regards, 

Columbia University and Sage Bionetworks

For general inquiries or to request with your account, please email COVIDRecoveryCorps@cumc.columbia.edu

**Comment by alxdarksage** [comment]
Consent text has been updated for English and Spanish
