### ISSUE TITLE
Make sure we update the HIPAA Authorization messaging and .pdf once people have signed it. Spanish & English

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#213]
![Screen Shot 2020-05-16 at 3 58 57 PM](https://user-images.githubusercontent.com/64874011/82131818-292a2700-978e-11ea-914a-3b7a329db5c4.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@vbarone00   

This is what people see after they sign the HIPAA Authorization. Please advise on what messaging should go here and what that document should look like. 

Thanks !

**Comment by conundrumgirl** [comment]
@alxdarksage - just making sure you see this

**Comment by vbarone00** [comment]
@conundrumgirl will they receive the full pdf of the HIPPA authorization or just the signature page?

**Comment by vbarone00** [comment]
@conundrumgirl  For the email, we can remove CZI and put Columbia University.

**Comment by vbarone00** [comment]
For the HIPAA Authorization email:

Subject: Your HIPAA Authorization form for providing access to your Electronic Health Record

Hi,

For your reference, here's a copy of the HIPAA Authorization form you just signed to allow the COVID Recovery Corps study access to your Electronic Health Record (EHR).

Regards,

Columbia University and Sage Bionetworks

For general inquiries or to request with your account, please email COVIDRecoveryCorps@cumc.columbia.edu

For consent form email:

Subject: Your Consent Form for participating in the COVID Recovery Corps study
Hi,

For your reference, here's a copy of the consent form you just signed to participate in the COVID Recovery Corps study.

Regards,

Columbia University and Sage Bionetworks

For general inquiries or to request with your account, please email COVIDRecoveryCorps@cumc.columbia.edu

**Comment by alxdarksage** [comment]
Updated
