### ISSUE TITLE
Styling for hamburger menu

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#215]
![Screen Shot 2020-05-16 at 4 32 20 PM](https://user-images.githubusercontent.com/64874011/82132269-d3a44900-9792-11ea-9e6a-002c5d988ad2.png)

![btn_close_black](https://user-images.githubusercontent.com/64874011/82132230-5d074b80-9792-11ea-8397-482c0b624b07.png)

**Comment by mkellen** [comment]
The menu does not look like the image above. There is no drop shadow. The horizontal spacing bar has no margins. @flylikeabirdfloatlikeabuoy

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@mkellen   What we have today is fine. I asked them to update it because the top nav doesnt have drop shadow
