### ISSUE TITLE
Low priority: Top nav colors and font weight

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#216]
![Screen Shot 2020-05-16 at 4 40 49 PM](https://user-images.githubusercontent.com/64874011/82132376-03078580-9794-11ea-9c40-0b9d7d07846d.png)

Please make top nav bg: #FCFCFC

The bold rendering looks really weird, I was messing around in Firefox and I feel that the following might work better for: 
About.  Meet the ResearchersFAQsContact UsPrivacy Policy

font-weight: 400;
font-size: 1.6rem;

**Comment by conundrumgirl** [comment]
#286
