### ISSUE TITLE
URGENT!!  landing page on mobile has weird gradient beneath banner photos

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#221]
![IMG_29E2B9E53585-1](https://user-images.githubusercontent.com/64874011/82155389-6a234980-9829-11ea-9d70-395078061c4a.jpeg)

**Comment by jay-hodgson** [comment]
The gradient isn't the problem (that's there so you can read the white text on these images that have bright areas!).  The problem is that the text no longer fits in the image space.
Changing the font-size to 24px for mobile looks like it will fix it for your device.
