### ISSUE TITLE
IRB stamped versions of Consent and HIPPA Authorization

### ISSUE THREAD

**Issue by vbarone00** [Sage-Bionetworks/covidrecoverycorps#239]
[9_ChungWendy_AuthorizationtoUseandDisclosePHI_20200515-151454-p7mumrour_ CLEAN.pdf](https://github.com/Sage-Bionetworks/covidrecoverycorps/files/4646923/9_ChungWendy_AuthorizationtoUseandDisclosePHI_20200515-151454-p7mumrour_.CLEAN.pdf)
[11_ChungWendy_ConsentForm-Main_20200515-152030-crm8plygm CLEAN.pdf](https://github.com/Sage-Bionetworks/covidrecoverycorps/files/4646924/11_ChungWendy_ConsentForm-Main_20200515-152030-crm8plygm.CLEAN.pdf)
@alx @conundrumgirl These are the IRB stamped versions of the consent and HIPAA authorization

**Comment by conundrumgirl** [comment]
@vbarone00 , can you please enter the issues where the copy diverges from what we have on staging

**Comment by vbarone00** [comment]
Screen 1/13: What we will ask you to do?

Revise 4th paragraph to: 

If you have a positive test result for COVID-19, we may ask you to upload a picture or a scanned copy of the document to the study website. This is optional and not required to take part in the study.

Screen 5/13: What are the risks?
Please move the following revised paragraph to the first paragraph:

If you give a blood sample, the most common risks are brief pain and bruising. Some people may become dizzy or feel faint. There is also a small risk of infection. You might feel uncomfortable about a fecal swab or a nose swab. The nose swab might feel uncomfortable for a few seconds.

Screen 7/13 - What will you do with my data and samples?

Revise title to: What will you do with my data and samples?

Replace text with:
We will store your data and samples securely. Your data will be stored in the COVID Recovery Corps database in the Sage Bionetworks “cloud” and your biosamples will be stored in the COVID Recovery Corps Biobank at Columbia University. The database will have your individual data and the biobank will store your samples like your blood, and pee. 
 
To protect your data, we will use a code to identify your data and samples rather than your name or other personal information. This code cannot be used to directly identify you. This coded data is known as de-identified data. Only key people from our study team can link your identity to your study. 
 
We will use the data and samples to make discoveries about COVID-19. We will study who got infected with the virus and why some people responded differently than others. We will also study changes in health after people have recovered from COVID-19. You can learn more about the research we are doing at [](http://covidrecoverycorps.org).

Screen 8/13- Sharing your data with future researchers

Add this sentence to the last paragraph: That research will not include whole-genome sequencing.

Screen 11/13- Leaving the study

Replace first paragraph with:
Taking part in COVID Recovery Corps is voluntary. You can choose to join or not. No matter what you decide, now or in the future, it will not affect how your doctor treats you, and it will not result in any penalty or loss of benefits to which you are otherwise entitled.

Screen 13/13- How to contact us? 

Replace with: 
For general questions, concerns, or complaints, please contact the COVID Recovery Corps study at 212-305-5700 (24 hours) or [COVIDRecoveryCorps@cumc.columbia.edu.](url)

For questions about your rights as a research participant, concerns or complaints, please contact Western IRB (WIRB) at [help@WIRB.com](url) at 360-252-2500 or toll-free 800-562-4789.

For Consent signature page

Replace last checkbox copy with:
**I have read this consent form (or someone read it to me). I understand the information in this form. All of my questions have been answered. I freely and willingly choose to take part in COVID Recovery Corps study.**

**Comment by alxdarksage** [comment]
Electronic versions have been updated to include this content, minus the interactive part at the bottom which is handled electronically.
