### ISSUE TITLE
Please match Login experience with the Getting started page 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#251]
Please remove the question "How would you like to login?" 
Please add a link underneath the login input labeled "Sign up for an account" that sends them to the Join us eligibility page in case they got here but realize they haven't joined. 

Please match Login experience with the Getting started screen and the Don't have email? screen in terms of the input container:

![Screen Shot 2020-05-18 at 6 02 16 PM](https://user-images.githubusercontent.com/64874011/82273381-3718ad00-9932-11ea-9d80-715176b81763.png)

![Screen Shot 2020-05-18 at 6 09 48 PM](https://user-images.githubusercontent.com/64874011/82273610-c4f49800-9932-11ea-981b-49dc0394c9ef.png)

Colors and updates are here: 

![](https://user-images.githubusercontent.com/64874011/82130371-a69a6b00-977f-11ea-96da-b38827701937.png)

**Comment by jay-hodgson** [comment]
@flylikeabirdfloatlikeabuoy Wait, are there 2 links under the email field then?  One to send to join (Sign up for an account) and one to Sign in via phone number (I want to sign in with my phone number)?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@jay-hodgson  Not sure if I follow your question. 

When the user hits "join us" -->they see eligibility questions ---> if they pass, then we show Getting Started page which we prioritize with email---> If they don't have email, we give them option for phone setup . 

In the Login screen, by default we have Email tab opened but they can tab to phone.
In case they meant to press "Join Us" rather than "Log in", we should add "Sign up for an account" link which sends them to the eligibility questions. 

Please let me know if that helps clarify the flow.

**Comment by jay-hodgson** [comment]
@flylikeabirdfloatlikeabuoy : Ahh, now I understand.  I was confused by
> Please match Login experience with the Getting started screen and the Don't have email? screen in terms of the input container...
I thought you meant to default to email login, and hide the phone login (like registration).  Thank you!

**Comment by jay-hodgson** [comment]
Looks like @conundrumgirl  already fixed the content, and my changes to the site-wide styles have fixed the majority of the issues around fonts/styling.
The most noticeable different (from what I could see) was around button width.  The Submit button (during registration) was full width, and the other buttons were only wide enough to fit their text content (not extra wide like the design).
