### ISSUE TITLE
Urgent!! Per Mike's request: please add text below Contact information

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#252]
![Screen Shot 2020-05-18 at 6 16 51 PM](https://user-images.githubusercontent.com/64874011/82273985-c1addc00-9933-11ea-8e26-9191a9dad872.png)

"This information is only used to manage your interactions with the study team, and will not be distributed to third parties."

**Comment by conundrumgirl** [comment]
#262
