### ISSUE TITLE
URGENT!! Please add withdrawal survey per Mike's request

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#254]
After user withdraws from study, we are surfacing the farewell message. Please add a one question survey so that we can gather data on why they are withdrawing: 

Same formatting as survey questions 

"Please help us make the COVID Recovery Corps study better by telling us about your reasons for withdrawing. (Check all that apply)"

Study was taking too much of my time
Not enough benefit for me to continue
I am concerned about my privacy 
I am concerned about the use of my data
Withdrawing for personal reason that do not involve this study

Thanks! 
![Screen Shot 2020-05-18 at 6 38 34 PM](https://user-images.githubusercontent.com/64874011/82275232-09823280-9937-11ea-87d5-3fdcff5fd50b.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Updating based on Alina's comment around inability to collect survey data after they have consented. 

![Screen Shot 2020-05-18 at 9 30 05 PM](https://user-images.githubusercontent.com/64874011/82284803-be741980-994e-11ea-82c4-e50385d547de.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
please use checkboxes! 
![Screen Shot 2020-05-19 at 10 29 44 AM](https://user-images.githubusercontent.com/64874011/82358702-bc946f80-99bb-11ea-8ef4-9d56a191662e.png)

**Comment by conundrumgirl** [comment]
#266
