### ISSUE TITLE
Add new symptom questions to survey2

### ISSUE THREAD

**Issue by conundrumgirl** [Sage-Bionetworks/covidrecoverycorps#258]
![image](https://user-images.githubusercontent.com/5190623/82342443-797bd180-99a6-11ea-9069-814acb6a03a2.png)

**Comment by conundrumgirl** [comment]
#261

**Comment by mkellen** [comment]
mostly done, but the item just states "conjunctivitis". It should be "conjunctivitis (red eyes)"
