### ISSUE TITLE
Account Settings text formatting

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#267]
Please add following text to "learn more" section of account settings

Share my data with researchers:

"You will have the opportunity to share your data with qualified researchers outside of the COVID Recovery Corps. 

All qualified researchers must be approved by the COVID Recovery Corps study team and will only use de-identified data. This de-identified data does not contain identifiers like name, date of birth, or zip code. 

These researchers may be from outside the United States and may work for a non-profit institution, commercial drug or medical device companies, or be a private citizen.

Sharing your data with qualified researchers is optional and you can change your mind at any time by updating your data sharing options in your profile. 

But once we share your data we cannot get it back. If you decide to end data sharing, we will not share your future data."
![Screen Shot 2020-05-19 at 2 11 05 PM](https://user-images.githubusercontent.com/64874011/82378753-9500cf80-99da-11ea-8bc9-520e88db5c20.png)

**Comment by conundrumgirl** [comment]
#279

**Comment by mkellen** [comment]
The text is added, but the formatting is really bad on a desktop browser (Chrome). The paragraphs lay out horizontally instead of vertically
