### ISSUE TITLE
URGENT!! Account settings lorem ipsum for HIPAA

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#268]
Please add into learn more of HIPAA section of Account settings:

"Sharing your EHR (electronic health records) is optional.

Your electronic health record (EHR) is a digital version of your medical health record (which may include information like your doctor’s notes from visits, diagnosis information and medications). 

If you say yes to sharing, we will see data about your health problems, test results, medical procedures, images (such as X-rays), and medicines you take. 

It may tell us about your mental health, genetic conditions, or use of alcohol or drugs. EHR may contain sexual or infection data, including HIV status. You can say no to sharing your health records and still take part in COVID Recovery Corps. 

There will be a separate form called a HIPAA Authorization for you to sign if you decide to give us access to your health records. "
![Screen Shot 2020-05-19 at 2 12 12 PM](https://user-images.githubusercontent.com/64874011/82378848-bcf03300-99da-11ea-8353-cff8d6c4b424.png)

**Comment by conundrumgirl** [comment]
#267

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-20 at 10 49 39 AM](https://user-images.githubusercontent.com/64874011/82479870-d26f6680-9a87-11ea-92aa-13da30ef0135.png)

There's some weird column thing happening on the body of learn more
