### ISSUE TITLE
Please an extra paragraph spacing between Yes and No option for data sharing

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#271]
![Screen Shot 2020-05-19 at 2 50 36 PM](https://user-images.githubusercontent.com/64874011/82382033-1c047680-99e0-11ea-8d0a-5d069885f6d9.png)

Right now the two options seems too close together

**Comment by conundrumgirl** [comment]
#282
