### ISSUE TITLE
URGENT!  Typo on consent signature screen: "concent" -->"consent." Please also center align text

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#273]
![Screen Shot 2020-05-19 at 3 41 46 PM](https://user-images.githubusercontent.com/64874011/82385574-4279e000-99e7-11ea-974b-c7372286c93f.png)

Please center align text and body copy

**Comment by conundrumgirl** [comment]
#281
