### ISSUE TITLE
Dashboard survey 1 has a weird underline hyperlink on hover in chrome ??

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#275]
![Screen Shot 2020-05-19 at 3 50 02 PM](https://user-images.githubusercontent.com/64874011/82386091-828d9280-99e8-11ea-9336-d00557a52433.png)

**Comment by conundrumgirl** [comment]
can't reproduce. @flylikeabirdfloatlikeabuoy - are you still seeing this?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
nope
