### ISSUE TITLE
URGENT!! Please swap out Privacy Policy .pdf with this .pdf

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#276]
[COVID_website_Updated Privacy Policy.pdf](https://github.com/Sage-Bionetworks/covidrecoverycorps/files/4653766/COVID_website_Updated.Privacy.Policy.pdf)
Verified by Vanessa

**Comment by conundrumgirl** [comment]
#280
