### ISSUE TITLE
Urgent! Consent- Summary Screen issues

### ISSUE THREAD

**Issue by vbarone00** [Sage-Bionetworks/covidrecoverycorps#277]
Screen 1/13- About the study
Bold the following: collect information from participants who have been diagnosed or believe they have had COVID-19.

Screen 2/13- What will I be asked to do?
Revise to: The **first 4 surveys** may take up to **30-60 minutes total**. On a **monthly basis**, we will contact you to complete a **15-minute survey**.

Add a return(new paragraph) between: You can pick "Prefer not to answer" for any of the questions.

Revise the last sentence to: We also may contact you to invite you to participate in other COVID-related research studies.

Screen 5/13- What are the risk?
Revise to:
However, if there is a **data breach** it may be possible to **identify you and your sensitive information** may be seen by someone without your permission.

Screen 8/13-Sharing your data with future researchers
Revise:
All qualified researchers must be approved by the COVID Recovery Corps study team and will only use de-identified data.

Revise to:
These researchers may be from **outside the United States** and may work for a **non-profit institution, commercial drug or medical device companies, or be a private citizen.**

Revise to:
Sharing your data with qualified researchers is optional and you can change your mind at any time by updating your data sharing options in account settings.

Screen 10/13: Not Medical Care
Revise to:
If you have **questions or concerns** related to your health, you should **contact your doctor.**

Screen 11/13: Leaving the Study
Revise to:
If you decide to withdraw (quit) the study, you can tell us by going to the website and by clicking the **"Withdraw from study" in account setting.** You can also also**email or write to us**.

If you withdraw, **your samples will be destroyed**. Your **data will not be distributed anymore**.

However, if researchers already have your data or samples for their studies, the COVID Recovery Corps study cannot get it back.

Screen 12/13: Things you should consider before you say yes
Revise to: 
Before you say yes to joining the study, please consider the following:  (Remove bold)

Screen 13/13: How to contact us?
Revise to:

**For general questions, concerns, or complaints,** please contact the COVID Recovery Corps study at 212-305-5700 (24 hours) or [COVIDRecoveryCorps@cumc.columbia.edu](url).

**For questions about your rights as a research participant, concerns or complaints**, please contact Western IRB (WIRB) at help@WIRB.com at 360-252-2500 or toll-free 800-562-4789

Remove... For questions related to the website, your account, or other technology issues, please contact Sage Bionetworks at [TODO: John to provide]

**Comment by vbarone00** [comment]
For Consent signature page

Replace last checkbox copy with:
**I have read this consent form (or someone read it to me). I understand the information in this form. All of my questions have been answered. I freely and willingly choose to take part in COVID Recovery Corps study.**

**Comment by conundrumgirl** [comment]
@vbarone00 , I have updated the consent -- but can you please doublecheck. I wasn't 100% clear on some of the revisions
