### ISSUE TITLE
Urgent! Consent Quiz bug for all 2nd answer options in Full version

### ISSUE THREAD

**Issue by vbarone00** [Sage-Bionetworks/covidrecoverycorps#278]
If you are in the full version, when you click on the correct answer "To be able to better understand COVID-19", the button doesn't show up clicked.
<img width="917" alt="Screen Shot 2020-05-19 at 4 16 16 PM" src="https://user-images.githubusercontent.com/30300402/82387608-58d66a80-99ec-11ea-9063-f2d1c6f7becc.png">

**Comment by vbarone00** [comment]
<img width="780" alt="Screen Shot 2020-05-19 at 4 24 29 PM" src="https://user-images.githubusercontent.com/30300402/82387990-427cde80-99ed-11ea-9e8e-54f6652de248.png">

**Comment by conundrumgirl** [comment]
#281 #281
