### ISSUE TITLE
Weird bug: if user clicks Join us and already has an account, they are taken through consent flow again, 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#289]
I exited out of consent with "x" button. It took me to this screen. 

![IMG_9F53C19A997C-1](https://user-images.githubusercontent.com/64874011/82481961-f7190d80-9a8a-11ea-82b3-6782b0d5f59d.jpeg)

But as I navigated away from hamburger menu I was able to surface survey dashboard 

![IMG_2E7A35E67B55-1](https://user-images.githubusercontent.com/64874011/82482030-11eb8200-9a8b-11ea-9b02-3b5b56352ed1.jpeg)

**Comment by jay-hodgson** [comment]
@alxdarksage : If someone re-registers, is that account information reset?
