### ISSUE TITLE
Update consent text

### ISSUE THREAD

**Issue by jay-hodgson** [Sage-Bionetworks/covidrecoverycorps#29]
(once we receive new copy from Lynn)

**Comment by conundrumgirl** [comment]
I have updated consent on the main consent pages.
Will put in ehr. stuff from vanessa.

**Comment by jay-hodgson** [comment]
I thought this might be a duplicate of #44 (where I updated other consent text from vanessa in both consent pages that I could find).  Is that not the case?

**Comment by jay-hodgson** [comment]
@conundrumgirl : Is this done then?

**Comment by conundrumgirl** [comment]
I think it is done. Let's close it for now. I'm thinking of asking Vanessa to go through the site today to see if there are discrepancies and enter new issues if she finds them
