### ISSUE TITLE
Default handling of data sharing question during consent

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#290]
Currently, the option to not share data broadly is selected by default, and the website includes the text "By default, you are sharing your data with this study only."

We should remove this text, and not preselect either option to the data sharing question.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@mkellen  @vbarone00   

Hi Mike, Vanessa and I made the decision to preselect it by default because of that line ""By default, you are sharing your data with this study only" in the Consent form. And because currently there is no error statement that calls out that option. 

@vbarone00  Thoughts?

**Comment by mkellen** [comment]
I thought we had discussed and agreed to remove that line from consent, consistent with all prior Sage studies.

**Comment by vbarone00** [comment]
Leave the language for now but we can remove the preselection. But if they do not pick an option, they should not be able to move forward. They need to pick one to consent.

**Comment by mkellen** [comment]
John's indicated we can remove language indicating the default behavior. Is that OK?

They will need to pick an option to move forward.
