### ISSUE TITLE
Do not allow symptoms to be reported in the future

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#292]
On survey question 2a about dates of symptoms, the current UI allows you to enter any date in 2020 for end of symptoms. It doesn't make any sense to report a future date here.

Also, you can report both a last day of symptoms, and check the box that you still have symptoms. This also doesn't make sense.  

You should either not check the box that you still have symptoms and report a last day of symptoms in the past, OR you should check the box that you still have symptoms and the last day should be hard-coded to report the current date.

**Comment by mkellen** [comment]
Question 3a has the same problem: restrict reporting of dates to no earlier than the current date

**Comment by jay-hodgson** [comment]
If we can't dynamically set the max value in the schema that drives this form, would [custom validation](https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#custom-validation-rules) code work (the user would still be able to select a date in the future but would get an error on validation)?

**Comment by mkellen** [comment]
Also, I'm reporting this as a defect, but it's not a show stopper. If this turns into big effort we can pass on it.

**Comment by mkellen** [comment]
Good enough for now.
