### ISSUE TITLE
!!! URGENT!!! HIPAA Authorization signature page is actually the Study Consent, please match HIPAA Authorization 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#295]
![IMG_2AFBC5E33AA4-1](https://user-images.githubusercontent.com/64874011/82486555-e7e98e00-9a91-11ea-80a1-3b5e3adc50b0.jpeg)

@vbarone00   Please provide finalized HIPAA Authorization Signature page based on IRB

**Comment by vbarone00** [comment]
Replace with: 
**I know the following information may be gathered from my EHR:**
1. All health information pertaining to my medical history, mental or physical condition, and
treatment received
2. Mental health diagnosis or treatment information
3. HIV/AIDS testing information
4. Alcohol/drug abuse, diagnosis or treatment information
5. Genetic testing information
6. Information about domestic violence and sexual assault counseling

**By signing this form, I voluntarily authorize my healthcare providers and organizations to
share my EHR with the COVID Recovery Corps Research Study, led by Dr. Wendy Chung,
and its partner organization Sage Bionetworks.**
