### ISSUE TITLE
HIPAA- 10/10 Who can answer my questions?

### ISSUE THREAD

**Issue by vbarone00** [Sage-Bionetworks/covidrecoverycorps#298]
Replace:
For general questions, please contact the COVID Recovery Corps study at 212-305-5700 or COVIDRecoveryCorps@cumc.columbia.edu

For your rights as a research participant, please contact Western IRB (WIRB) at help@WIRB.com at 360-252-2500 or toll-free 800-562-4789.

With: 

- **For general questions**, please contact the COVID Recovery Corps study at 212-305-5700 (24 hours) or COVIDRecoveryCorps@cumc.columbia.edu

- **For questions about your rights as a research participant, concerns or complaints**, please contact Western IRB (WIRB) at help@WIRB.com at 360-252-2500 or toll-free 800-562-478

**Comment by mkellen** [comment]
Not updated on staging
