### ISSUE TITLE
URGENT!! Please remove pencil icon until they have entered information. 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#305]
![Screen Shot 2020-05-20 at 1 24 39 PM](https://user-images.githubusercontent.com/64874011/82493804-6ac41600-9a9d-11ea-837a-8bdd7fee480a.png)

Dashboard should have all empty circles. Once they've entered their Contact information, we surface pencil icon. 

Thanks

**Comment by conundrumgirl** [comment]
#328
