### ISSUE TITLE
Meet Researchers page

### ISSUE THREAD

**Issue by vbarone00** [Sage-Bionetworks/covidrecoverycorps#308]
Issue 1
Replace:
Led by Columbia University and Sage Bionetworks, the study aims to enable those who have recovered from COVID-19 to help scientists answer key questions - about how the body fights coronavirus and whether and how often infection affords immunity. Starting in the New York metropolitan area - the epicenter of the pandemic in the United States - participants will be part of a powerful dataset that may lead to scientific advances to help save lives.

With:
Led by Columbia University and Sage Bionetworks, the study aims to enable those who have recovered from COVID-19 to partner with scientists to answer key questions - about how the body fights coronavirus and whether and how often infection affords immunity. Starting in the New York metropolitan area - the epicenter of the pandemic in the United States - participants will help build a powerful dataset that may significantly advance science and help save lives. 

Issue 2
Replace: 
Dr. Wendy Chung is a co-Principal Investigator based at Columbia University with oversight over clinical operations. 

With:
**Dr. Wendy Chung is a co-Principal Investigator based at Columbia University with oversight over clinical operations.** 

Issue 3
Replace: 
She was recently featured in the documentary, The Gene: An Intimate History.

With:
She was recently featured in the documentary, [The Gene: An Intimate History.](https://www.pbs.org/show/gene/)

Issue 4
Replace:
Dr. Lara Mangravite is a co-Principal Investigator with oversight over technology, governance, and data commons.

With:
**Dr. Lara Mangravite is a co-Principal Investigator with oversight over technology, governance, and data commons.**

Issue 5:
Replace:
Founded by Dr. Priscilla Chan and Mark Zuckerberg
in 2015, the Chan Zuckerberg Initiative (CZI) is a new kind of philanthropy that’s leveraging technology to help solve some of the world’s toughest challenges — from eradicating disease, to improving education, to reforming the criminal justice system. Across three core Initiative focus areas of Science, Education, and Justice & Opportunity, we’re pairing engineering with grant-making, impact investing, and policy and advocacy work to help build an inclusive, just and healthy future for everyone.

With:
Founded by Dr. Priscilla Chan and Mark Zuckerberg in 2015, the Chan Zuckerberg Initiative (CZI) is a new kind of philanthropy that’s leveraging technology to help solve some of the world’s toughest challenges — from eradicating disease, to improving education, to reforming the criminal justice system. Across three core Initiative focus areas of Science, Education, and Justice & Opportunity, we’re pairing engineering with grant-making, impact investing, and policy and advocacy work to help build an inclusive, just and healthy future for everyone. For more information, please visit www.chanzuckerberg.com.

**Comment by jay-hodgson** [comment]
@conundrumgirl : so is this done?

**Comment by conundrumgirl** [comment]
@jay-hodgson - yes
