### ISSUE TITLE
URGENT!! Survey 4: Q2: if people only have a few family members, they shouldn't have to fill out "0" for the other inputs. 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#316]
![Screen Shot 2020-05-20 at 3 46 24 PM](https://user-images.githubusercontent.com/64874011/82504786-11fe7880-9ab1-11ea-9716-1c32ada4e423.png)

If say you have 3 of 65-79 years old and 1 under 3 years old, we shouldn't make people type "0" everywhere else in order to move on.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Run into similar problem here:

![Screen Shot 2020-05-20 at 3 51 30 PM](https://user-images.githubusercontent.com/64874011/82505097-c8625d80-9ab1-11ea-8157-c29278fd8db9.png)

**Comment by conundrumgirl** [comment]
added defaults
