### ISSUE TITLE
Survey 4: Q 14. Left margin issue . Can we add a drop down arrow so people know they have to select from it? 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#319]
I guess that might be a generic question all around for these drop down. 

![Screen Shot 2020-05-20 at 4 01 18 PM](https://user-images.githubusercontent.com/64874011/82505852-2b082900-9ab3-11ea-9f6b-123b1802f5d1.png)

**Comment by conundrumgirl** [comment]
This one was supposed to be a radio button like the others. Fixed
