### ISSUE TITLE
Survey 4 Q20: Please provide ability to "prefer not to answer" or make it optional

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#323]
![Screen Shot 2020-05-20 at 4 08 24 PM](https://user-images.githubusercontent.com/64874011/82506250-25f7a980-9ab4-11ea-909e-cdf80c3ae0fa.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@vbarone00  Thoughts?

**Comment by conundrumgirl** [comment]
made it optional
