### ISSUE TITLE
Address verification

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#348]
Can we add address verification / type ahead.

From CZI.  Not a launch requirement, becomes more important once we start shipping test kits.

**Comment by jay-hodgson** [comment]
Is this going to be shipped via USPS?  If so, we could use their service pretty easily I think.
https://www.usps.com/business/web-tools-apis/address-information-api.htm
We would need to create our own Web Tools User ID, but I found an example and tried a few tests to see the possible responses:

### Valid address test:

> GET http://production.shippingapis.com/ShippingAPI.dll?API=Verify&XML=%3CAddressValidateRequest%20USERID=%22826ADISY3274%22%3E%3CAddress%3E%3CAddress1%3E%3C/Address1%3E%3CAddress2%3E2901%203rd%20Ave%20%23330%3C/Address2%3E%3CCity%3ESeattle%3C/City%3E%3CState%3EWA%3C/State%3E%3CZip5%3E%3C/Zip5%3E%3CZip4%3E%3C/Zip4%3E%3C/Address%3E%3C/AddressValidateRequest%3E

```
<AddressValidateResponse>
<Address>
<Address2>2901 3RD AVE STE 330</Address2>
<City>SEATTLE</City>
<State>WA</State>
<Zip5>98121</Zip5>
<Zip4>1031</Zip4>
</Address>
</AddressValidateResponse>
```

### Vague address test:

> GET http://production.shippingapis.com/ShippingAPI.dll?API=Verify&XML=%3CAddressValidateRequest%20USERID=%22826ADISY3274%22%3E%3CAddress%3E%3CAddress1%3E%3C/Address1%3E%3CAddress2%3E3rd%20Avenue%3C/Address2%3E%3CCity%3ESeattle%3C/City%3E%3CState%3EWA%3C/State%3E%3CZip5%3E%3C/Zip5%3E%3CZip4%3E%3C/Zip4%3E%3C/Address%3E%3C/AddressValidateRequest%3E

```
<AddressValidateResponse>
<Address>
<Error>
<Number>-2147219403</Number>
<Source>clsAMS</Source>
<Description>Multiple addresses were found for the information you entered, and no default exists.</Description>
<HelpFile/>
<HelpContext/>
</Error>
</Address>
</AddressValidateResponse>
```

### Invalid address test:

> GET http://production.shippingapis.com/ShippingAPI.dll?API=Verify&XML=%3CAddressValidateRequest%20USERID=%22826ADISY3274%22%3E%3CAddress%3E%3CAddress1%3E%3C/Address1%3E%3CAddress2%3EInvalid%3C/Address2%3E%3CCity%3ESeattle%3C/City%3E%3CState%3EWA%3C/State%3E%3CZip5%3E%3C/Zip5%3E%3CZip4%3E%3C/Zip4%3E%3C/Address%3E%3C/AddressValidateRequest%3E

```
<AddressValidateResponse>
<Address>
<Error>
<Number>-2147219401</Number>
<Source>clsAMS</Source>
<Description>Address Not Found. </Description>
<HelpFile/>
<HelpContext/>
</Error>
</Address>
</AddressValidateResponse>
```

**Comment by jay-hodgson** [comment]
There are references to this API having significant downtime, but I don't actually see that in the [current data](https://www.shippingapimonitor.com/history.html?api=usps) (so maybe they fixed their services?).

**Comment by jay-hodgson** [comment]
Since there isn't a commitment to a particular shipping service, maybe the best thing we can do to improve data going into the system is to use the Google [Places API](https://developers.google.com/maps/documentation/javascript/places-autocomplete), where I think we can get up to [100k requests per month for free](https://developers.google.com/places/web-service/usage-and-billing) (I think this is basic data).

**Comment by conundrumgirl** [comment]
This is another alternative: https://smartystreets.com/pricing/us-autocomplete-pro
It's not free $100/mo. for 30,000 lookups seems like a decent deal

**Comment by jay-hodgson** [comment]
@mkellen : My changes add address validation, but do not add type-ahead functionality.

**Comment by mkellen** [comment]
I entered an invalid address, and got what a user would consider a pretty unclear message:

Error
submission error Failed to fetch

Need to provide better feedback on an invalid mailing address

**Comment by mkellen** [comment]
Actually, can't get a valid address to go through.  I am using

20 W 34th St
New York NY, 10001

(The empire state building) Although maybe this is invalid because I don't have an apartment number? Can't tell

**Comment by jay-hodgson** [comment]
It's a mixed content issue (USPS uses http only, and we host on https).  Didn't see this during local development since I'm serving on http.  Darn...

**Comment by jay-hodgson** [comment]
Let's try this again...

**Comment by jay-hodgson** [comment]
(Should be ready for testing in about 15 minutes)
