### ISSUE TITLE
Add user preferences -- withdraw from study 

### ISSUE THREAD

**Issue by conundrumgirl** [Sage-Bionetworks/covidrecoverycorps#35]
![image](https://user-images.githubusercontent.com/5190623/81093956-af558c00-8eb7-11ea-9b0c-512e284e559d.png)

https://www.figma.com/file/NYYPVfRsbtUflNyySnFeDK/COVID_flow?node-id=482%3A770

**Comment by conundrumgirl** [comment]
@jay-hodgson  - I think this is a right API for withdrawal but please verify with @alxdarksage 
https://developer.sagebridge.org/swagger-ui/index.html#/_For%20Consented%20Users/withdrawConsentFromSubpopulation
This is the  ui for participant management. Will probably be helpful:
https://research.sagebridge.org/?p.offsetBy=0#/participants
If you don't have an account @alxdarksage will make you one

**Comment by jay-hodgson** [comment]
First toggle.  Toggling ON will redirect to consent page (I think).  Toggling OFF should change the sharingScope: https://developer.sagebridge.org/swagger-ui/index.html#/Participants/updateUsersParticipantRecord

Second toggle: Toggling ON will redirect to HIPPA authorization consent page (I think).  Toggling OFF should call https://developer.sagebridge.org/swagger-ui/index.html#/Consents/withdrawConsentFromSubpopulation

Withdraw from study: Should show a confirmation dialog.  On confirm, call
https://developer.sagebridge.org/swagger-ui/index.html#/Consents/withdrawParticipantFromStudy and show success message (if successful!) (and a way to go back to the home page?).

**Comment by jay-hodgson** [comment]
Spent a long time this morning trying to apply a nested "dark mode" theme to this page (https://material-ui.com/styles/advanced/#theme-nesting), by wrapping the AccountSettings page  route.  It's not taking effect, so I think I'll punt on this style for now and focus on making it work (already spent a couple of hours on this!).
