### ISSUE TITLE
Leadership page typos

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#351]
1. Please uppercase "leadership" - because other pages, like Privacy Policy - have the header uppercased. 
2. In the "Study leadership section" there are 3 en dashes (-) Please change to em dashes —
3. Under Wendy's section - it says patient and family led Please change to patient- and family-led 
4. Under Wendy's section - www.columbia.edu opens not in a new page, unlike the Gene link. Suggest opening in a new tab (I also suggest doing this for the Sage Bionetworks, Survivor Corps, and CZI links on this page)
5. add the CZI logo in the CZI section at the bottom

**Comment by jay-hodgson** [comment]
@mkellen 

> Under Wendy's section - it says patient and family led Please change to patient- and family-led

So change to 

> She works with many patient- and family-led organizations to develop
???

**Comment by mkellen** [comment]
Yeah, that's what CZI's copy editor wrote. I agree it looks awkward. Suggest this larger wording re-work:

She works with many patient and family led organizations to develop better supports and treatments for rare diseases and was recognized by the National Organization of Rare Disorders with the Rare Impact Award in 2019. 

To

She works with many organizations to improve the support and treatment of rare disease for patients and family members. Dr. Chung was recognized by the National Organization of Rare Disorders with the Rare Impact Award in 2019.
