### ISSUE TITLE
Survey Typos

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#357]
1. Survey 2 (1/6) - Uppercasing is inconsistent - A few things - should it be COVID-19 and not just COVID? Let's lowercase everything but the first word - so "Loss of conciousness" "Shortness of breath" - and make that consistent throughout (Chest pain, Night sweats) -- same also for the next page. (Nasal swab...etc.)

2. Survey 3 (3/6) - I Don't Know change to I don't know

3. Survey 3 (4/6) - I Don't Remember, Heart Attack - I don't remember, Heart attack (again, just consistency throughout) 

4. Survey 4 (2a/6) - E.G., infection ff - e.g., infection "of"

5. Survey 4 (3/6) - Twice a year of more - Twice a year or more

6. Survey 4 (6/6) - What is your job title - What is your job title?

**Comment by mkellen** [comment]
Has been marked as fix-not merged for a while, can we get this deployed?

**Comment by conundrumgirl** [comment]
@mkellen  - it is on staging.
I am not 100% sure about some of the items e.g.  'lowercase everything but the first word' since there is a large number of instances. But I think I got most of them
