### ISSUE TITLE
URGENT!! Top nav not operating dynamically and interferes with ability to go back

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#364]
The dark top nav on tablet and phone in the survey sections has been acting strangely. it would disappear as I scrolled back up and shown slightly off the screen - making it difficult to navigate back to the dashboard since the main nav bar peeks out below beneath it and interferes with its interaction. 

Please make the Survey's top nav non dynamic. The main nav bar should not be there during surveys.

Thanks,

**Comment by jay-hodgson** [comment]
@flylikeabirdfloatlikeabuoy : Ok to make this "non dynamic" (removing attempt to hide while scrolling down) across the site (consent, account settings, ...), to fix this weirdness?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
yes please
