### ISSUE TITLE
Feedback on site photos

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#366]
1. Meet the researchers Page - The photo is quite large and since it does not have text it's not really a masthead...consider adding text above the fold
2. Home page - photo of elderly couple you can't see the bottom with the computer screen they are waving at

**Comment by jay-hodgson** [comment]
@flylikeabirdfloatlikeabuoy : add text above the fold?

**Comment by mkellen** [comment]
Maybe move the text "The COVID Recovery Corps is a citizen-powered research study to learn more about COVID-19 and make progress in the global fight." to overlay the image?  

I'm not sure exactly what is intended by the feedback, or even if the person has a specific solution.

Agree we could use design to look at the page and decide if any tweaks are needed.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
yeah we can do that.

This photo needs to be adjusted in photoshop in any case...let me play around with its saturation.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@jay-hodgson   Can we swap out the highly saturated photo for this less intense one? 
Thanks: 
![scientists](https://user-images.githubusercontent.com/64874011/82938419-a6039080-9f46-11ea-9330-22f29a89f1dc.jpg)
