### ISSUE TITLE
More survey typos / tweaks

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#369]
1. Survey 2: Do you smoke? -> Do you smoke tobacco?

2. Survey 2, Page 2: Do not allow for 2019 as year of response

3. Q13, 14, 15, 17 - Add the option "None of the above"

4. Q2: Q2  How many people live with you in your apartment/house in each age category? Include yourself. (Fill in 0 if none are)* -> Q2  How many people (including yourself) live with in your apartment/house in each age category?  (Fill in 0 if none are)*

**Comment by conundrumgirl** [comment]
#3 is Survey3
#4 asks for "Q2 How many people (including yourself) live with in your apartment/house in each age category? (Fill in 0 if none are)*" I assume there is a typo and what the copy should be is "How many people (including yourself) live in your apartment/house in each age category? (Fill in 0 if none are)"
