### ISSUE TITLE
Home Page copy

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#370]
Header text says "A citizen-powered movement to drive scientific breakthroughs and save lives in the fight against COVID-19." -> Header text should say "Building a partnership between COVID-19 survivors and researchers to drive scientific breakthroughs in the fight against this disease."

**Comment by mkellen** [comment]
Eligibility:

2. When you click Join Us, you are taken to a page that says "To be eligible to take part in the COVID Recovery Corps Study, you must fulfill the following:" -> Since it says eligibility right above this sentence, please change to "To take part in the COVID Recovery Corps study, you must fulfill the following:"
Also study doesn't need to be capitalized

3. The page asks for your zip code, but I think we need to clarify again here where participants must live in order to take part. You only learn that participants must be w/in 25 miles of CUMC if you enter an out of range zip code. -> Where it says "Please enter your zip code" we should add some context. "Please enter your zip code. Please note, we are only able to enroll participants who live within a 25 mile radius of the Columbia University Medical Center, located at XX address"

**Comment by mkellen** [comment]
I see #1 and #2 fixed, but not #3

**Comment by jay-hodgson** [comment]
> I see #1 and #2 fixed, but not #3
@mkellen : #375 to track the third item in this list.

**Comment by jay-hodgson** [comment]
(@mkellen noted that item 1 and item 2 are verified, so removing the "needs verification" label)
