### ISSUE TITLE
Screen cropping issue

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#372]
From Wendy: Question not completely visible on computer screen.  ends after check all. Q13 and Q15 can not read full question

From Mike: I can't repro this, am not sure what the issue is, we can ask in next call. Opening issue to track.

**Comment by mkellen** [comment]
Wendy report this occurring with Edge browser

**Comment by conundrumgirl** [comment]
I can not recreate it on browserstack

**Comment by conundrumgirl** [comment]
I was able to recreate on a windows machine and put in a fix. I'll have Wendy verify
