### ISSUE TITLE
Add survivor corps logo to meet the researcher page

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#386]
Consider adding their logo in the same format as other logos on this page

**Comment by jay-hodgson** [comment]
Sounds good to me, do you agree @flylikeabirdfloatlikeabuoy (and shall I just grab the logo from [their website](https://www.survivorcorps.com/) header?)?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
yeah I had suggested this... but I guess Hayley wasn't happy with their logo in general and had opted to not include it....treading on thin water on this one....

**Comment by jay-hodgson** [comment]
After some discussion, decided to hold off on implementing this right now.  Will close, but we can reopen if funders suggest it should be added.  Thank you.
