### ISSUE TITLE
minor: Please use same "x" for hamburger tray as the consent forms and let's remove drop shadow.

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#387]
Sorry, I forgot to update the mock up to match the top nav which doesn't have a drop shadow anymore. Please remove it from hamburger tray. 

Seems like this "x" is different than the other "x"s we're using in the consent forms. Please match consent forms. 

Thanks, 

![Screen Shot 2020-05-26 at 5 15 41 PM](https://user-images.githubusercontent.com/64874011/82962263-93a04b80-9f74-11ea-9c4e-08a59ebdf956.png)

**Comment by jay-hodgson** [comment]
The 'x' we're using in the consent forms (in the FloatingToolbar) is apparently a png of a white 'x', which does not work well on white.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-27 at 3 37 27 PM](https://user-images.githubusercontent.com/64874011/83079130-01f61400-a030-11ea-81da-7e92c9ef0374.png)

Could we just use Material Design's "X" https://material.io/resources/icons/?icon=timer&style=baseline

**Comment by jay-hodgson** [comment]
Probably.  I've grabbed the svgs directly from your design instead (so it's crisp, just as it would be by using the material.io font)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
GIThub doesn't allow .svg uploads for some weird reason...here's a zipped file of the black version of close button in that case. 

[btn_close_black.svg.zip](https://github.com/Sage-Bionetworks/covidrecoverycorps/files/4692191/btn_close_black.svg.zip)

**Comment by jay-hodgson** [comment]
@flylikeabirdfloatlikeabuoy : No reason to upload svg or zip to github.  Again, I already grabbed the svgs directly from your design.
