### ISSUE TITLE
TBD : update timing estimates for surveys and action items 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#388]

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@vbarone00 

I tried to read and go through every question really slow.
Here are my suggestions on time:

Contact Information: 2 minutes
Survey 1: 2 minute
Survey 2: 5 minutes
Survey 3: 5-7 minutes
Survey 4: 5-7 minutes


![Screen Shot 2020-05-27 at 11 15 31 AM](https://user-images.githubusercontent.com/64874011/83057152-618df880-a00b-11ea-8de9-123d4711ae7f.png)

**Comment by mkellen** [comment]
I see 5-10 for surveys 3 and 4, but that makes more sense to me

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@conundrumgirl  Let's go with 5-10 surveys for 3 and 4 to be safe. Thanks
