### ISSUE TITLE
Please add none of the above to Survey 2: Q. 4b

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#395]
![Screen Shot 2020-05-27 at 10 42 46 AM](https://user-images.githubusercontent.com/64874011/83054206-e62a4800-a006-11ea-9007-c64637cfa6fb.png)

**Comment by mkellen** [comment]
Not fixed on staging

**Comment by conundrumgirl** [comment]
![image](https://user-images.githubusercontent.com/5190623/83179862-720ba500-a0d7-11ea-9b46-46bdfbd6aaa9.png)
It must have been overwritten somehow - there is a fix in the commit.
