### ISSUE TITLE
Please add none of the above to : Survey 2: Q5 and 6

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#396]
Q5 currently has "none" ---> "None of the above" to be consistent
Q6 missing that option.

![Screen Shot 2020-05-27 at 10 51 48 AM](https://user-images.githubusercontent.com/64874011/83055042-2a6a1800-a008-11ea-89e2-e1ad3e0b5280.png)
![Screen Shot 2020-05-27 at 10 51 39 AM](https://user-images.githubusercontent.com/64874011/83055046-2c33db80-a008-11ea-973f-c8aec7361c46.png)

**Comment by mkellen** [comment]
This does not look fixed to me

**Comment by conundrumgirl** [comment]
Sorry. Closed the wrong issue. Looks fixed on staging to me now.

**Comment by mkellen** [comment]
On question 6, the option "Don't Know" should be an exclusive check box - it should behave the same way selecting "None of the above" or "Don't know"
