### ISSUE TITLE
Minor: please remove "." from responses in Survey 2, Q7 and 7a

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#397]
![Screen Shot 2020-05-27 at 10 54 14 AM](https://user-images.githubusercontent.com/64874011/83055301-87fe6480-a008-11ea-8df7-c8d2433a0b02.png)

**Comment by mkellen** [comment]
Not fixed on staging

**Comment by conundrumgirl** [comment]
![image](https://user-images.githubusercontent.com/5190623/83181524-dd567680-a0d9-11ea-9632-9febb15aa10b.png)

I assume by 7a it was meant  8

**Comment by conundrumgirl** [comment]
refixed and verified on staging.
