### ISSUE TITLE
Survey 3, Q10a. Add "None of the above" as an option please

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#403]
![Screen Shot 2020-05-27 at 3 25 27 PM](https://user-images.githubusercontent.com/64874011/83078408-69ab5f80-a02e-11ea-81e4-5fd566ef7f8e.png)

**Comment by mkellen** [comment]
It doesn't make sense to have "No Drugs" and "None of the above" as different options to me.  The latter is more consistent with the rest of the survey. 

Suggest we eliminate the "No Drugs" option?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Yeah the "None of the above" option is a relatively new implementation, so this update makes sense to match.

**Comment by conundrumgirl** [comment]
My reason for keeping 'no drugs' was that 'none of the above' might mean that they are on some drug not listed since we don't have the 'other' option. But I don't feel strongly

**Comment by flylikeabirdfloatlikeabuoy** [comment]
So maybe it's the wording...
"No drugs prescribed."

**Comment by mkellen** [comment]
It's also the ordering. Currently, none of the above applies to "No drugs"

What if we change to the following:

What drugs prescribed by a physician do you use for diabetes?
Insulin
Pills
Insulin and Pills
Prescribed something else
Not prescribed anything

**Comment by flylikeabirdfloatlikeabuoy** [comment]
This new order looks good to me. Could we rephrase the last two to be: 

What drugs prescribed by a physician do you use for diabetes?
Insulin
Pills
Insulin and Pills
Prescribed other medication 
No prescribed medication

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Yup, she accepts
