### ISSUE TITLE
Survey 4, Q18: please add none of the above.

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#407]

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-27 at 3 48 23 PM](https://user-images.githubusercontent.com/64874011/83079812-7f6e5400-a031-11ea-8ecb-f2022d4aecff.png)

**Comment by mkellen** [comment]
None of the above is now an option, but you can select it along with some of the other options.

Selecting none of the above should clear other selections. Selecting other options should deselect None of the above
