### ISSUE TITLE
URGENT!! Survey 3, Q5 should be radio buttons rather than a select all checkboxes

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#408]
![Screen Shot 2020-05-27 at 3 49 26 PM](https://user-images.githubusercontent.com/64874011/83079882-a88ee480-a031-11ea-85b1-677a92269cd4.png)

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy I don't think those should be exclusive.
It's possible that they go to more than one place
