### ISSUE TITLE
Survey exit confirmation dialog

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#414]
Please update these survey dialogs from: 
![image](https://user-images.githubusercontent.com/64874011/83083561-4b982c00-a03b-11ea-99e9-12f274c29c45.png)

To: 

Exit survey? 

Data you have entered may be not be saved.

[ Resume survey] [Exit survey] 

Bonus: if we're able to match the css to the rest of the site then I'd recommend: 
![Screen Shot 2020-05-27 at 4 56 09 PM](https://user-images.githubusercontent.com/64874011/83083626-7bdfca80-a03b-11ea-8f47-b219d4edc316.png)

**Comment by conundrumgirl** [comment]
This is a system alert dialog so we don't have much control over the look and feel.
I can change the main text though

**Comment by conundrumgirl** [comment]
The decision was to follow what we do for consent. Only have the confirmation when they click the dashboard. 
![image](https://user-images.githubusercontent.com/5190623/83186035-c10a0800-a0e0-11ea-821a-d3f8e055e873.png)
