### ISSUE TITLE
Country selection type-ahead

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#417]
Survey 4, question 1b

Would be nice to replace the free text entry of countries with a type-ahead enabled drop down list of valid country names to both decrease participant burden and amount of data cleaning needed.

**Comment by conundrumgirl** [comment]
I added the dropdown. It's not a type-ahead since it only goes to the first letter, but I think the country list is short enough for it to not be a major issue.
