### ISSUE TITLE
Update header banner text to below language

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#428]
Current text (to be replaced): If you live in the New York City metro area and have recovered from COVID-19, you can help scientists make progress in the global fight against this disease.

New text (replace with): If you live in the New York City metro area and have recovered from COVID-19 - or think you have - you can partner with scientists to better understand the recovery process and long term effects from this disease.

**Comment by conundrumgirl** [comment]
![image](https://user-images.githubusercontent.com/5190623/83288634-8cf21e00-a198-11ea-944a-2ba37a007dc4.png)
