### ISSUE TITLE
Add survivor corps logo to homepage 

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#429]
Please add to the right of Sage's logo. 

Logos can be accessed here https://drive.google.com/drive/folders/1xJ-j-DVgoQhYR0vpyibfMsEf1MTUURt8

**Comment by jay-hodgson** [comment]
See comments made in #431 about logos.  Added breakpoint for small screens, changed flex grid to column layout (to stack the logos) and align items in the center at the same point.
