### ISSUE TITLE
Homepage: update text to the right of people in labcoats

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#430]
Current text (to be replaced): You recovered. So have thousands of others. Your experience could help unlock the mysteries behind this disease. Our mission is to learn more about COVID-19 by bringing together the collective experiences of thousands of recovered patients.

New text (replace with): You recovered. Your experience could help unlock the mysteries behind this disease. Our mission is to learn more about COVID-19 by bringing together the collective experiences of thousands of recovered patients.

**Comment by conundrumgirl** [comment]
![image](https://user-images.githubusercontent.com/5190623/83288509-4e5c6380-a198-11ea-9063-094db311dce4.png)
