### ISSUE TITLE
Meet the researchers - Survivorcorps section - please update text and add logo

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#431]
Current text (to be replaced): Survivor Corps is a rapidly growing grassroots network of more than 45,000 COVID-19 survivors and family members who have first-hand experience with the virus. They are motivated to help others navigate the illness and find a pathway to recovery. Founded by Diana Berrent, Survivor Corps is mobilizing these survivors to donate plasma and to support ongoing scientific, medical and academic research to identify and improve treatments, understand the disease, and develop a vaccine.

New text (replace with): Survivor Corps is a rapidly growing grassroots
network of more than 50,000 COVID-19 survivors and family members who have first-hand experience with the virus. They are motivated to help others navigate the illness and find a pathway to recovery. Founded by Diana Berrent, Survivor Corps is mobilizing these survivors to donate plasma and to support ongoing scientific, medical and academic research to identify and improve treatments, understand the disease and its long term effects, and develop a vaccine.

Please also add logo (same format as columbia and sage). Logos can be accessed here https://drive.google.com/drive/folders/1xJ-j-DVgoQhYR0vpyibfMsEf1MTUURt8

**Comment by jay-hodgson** [comment]
pngs looked blurry when scaled, and eps not supported natively.  
Converted Survivor Corps eps logos to svg and removed namespaces ([unsupported in react, converted to camel case](https://github.com/facebook/react/issues/4908) and just removed metadata section).
