### ISSUE TITLE
Recent covid experience survey

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#435]
Question 5 on the recent covid experience survey only has space to share one "other" symptom. Per SurvivorCorps feedback participants may have more than one "other" symptom. Defer to Wendy/Sage on this one.
<img width="449" alt="Screen Shot 2020-05-29 at 10 42 36 AM" src="https://user-images.githubusercontent.com/47126880/83289812-72b93f80-a19a-11ea-85c8-4c0dfae49670.png">

**Comment by mkellen** [comment]
Superseeded by https://github.com/Sage-Bionetworks/covidrecoverycorps/issues/384
