### ISSUE TITLE
Dashboard time for medical history survey

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#436]
Dashboard says survey will take 15 minutes, per SurvivorCorps, survey takes no more than 10 minutes max. Consider updating.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@conundrumgirl 

Let's merge this ticket to this as well: https://github.com/Sage-Bionetworks/covidrecoverycorps/issues/388

Contact Information: 2 minutes
Survey 1: 2 minute
Survey 2: 5 minutes
Survey 3: 5-10 minutes
Survey 4: 5-10 minutes

Thanks!
