### ISSUE TITLE
Dashboard surveys

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#437]
Per SurvivorCorps - There is no communication to indicate that you have finished taking the surveys and that your survey results have been submitted. Any way to update this?

**Comment by conundrumgirl** [comment]
Not sure what's required for this. When all surveys are submitted the are disabled. There is a submit button on every survey so when you click it and are taken to the  dashboard and see the survey submitted, does that not provide enough of a feedback?

**Comment by mkellen** [comment]
Lynn, any ideas here, or do you agree nothing is needed?

**Comment by hayleybr00ks** [comment]
I wonder if adding a note like "Your survey has been submitted" before you are taken to the dashboard? No need to act on this one though, I think its OK as is.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Reopening with a solution for this issue. This has been brought up before so I want to make sure we address it. 

After user "submits" a survey they should be prompted with this confirmation screen.
 
Thanks! 

![Screen Shot 2020-06-02 at 10 02 49 AM](https://user-images.githubusercontent.com/64874011/83548191-39454480-a4b8-11ea-8069-a03f1cc4f401.png)

**Comment by conundrumgirl** [comment]
after talking to Lynn, we are removing the 'continue' button and keeping 'return to dashboard'
