### ISSUE TITLE
Welcome email went to spam folder

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#438]
Reported by SurvivorCorps team - not sure if theres a fix for this, but just flagging in case you want to look into it.

**Comment by jay-hodgson** [comment]
I'm curios to know what email service.  We should definitely ask anyone who registers for the site to be sure they mark the messages as Not Spam (to train each email service).  Not sure what else we can do, besides review the content of the email and try to make sure it doesn't look like spam (but that's what all spammers do too).

**Comment by hayleybr00ks** [comment]
Thanks @jay-hodgson - I just asked Diana (the person who reported this issue). Will let you know.

**Comment by hayleybr00ks** [comment]
The person who reported this issue uses microsoft outlook. Let me know if you have other questions. @jay-hodgson

**Comment by alxdarksage** [comment]
We use Simple Email Service and we've not been able to prevent these. Our reputation in SES is healthy with a low complaint rate. As Jay mentions, we should tell people to look in their spam folders for the sign-in email.
