### ISSUE TITLE
Recent covid experience survey

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#439]
I am able to skip questions 1-5 (did not record any answers and can move to the next page). Is there a reason why only some of these questions are required?

**Comment by conundrumgirl** [comment]
I thought that we agreed to make them optional since they are not selection rather free entry fields and adding a separate checkbox for the sole purpose of not answering seems awkward

**Comment by hayleybr00ks** [comment]
OK feel free to ignore this one then!
