### ISSUE TITLE
Recent COVID experience survey

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#441]
Feedback from Tania: the rating scale below seems to jump from zero to 3 (several) days on a few of the questions. Is there the option to add "a few" or "1-2 days" in between Not at all and Several Days. Additionally, "several days" and "more than half the days" feel too similar.

Similarly, in the last part of the survey:  "in the 2 weeks prior to becoming ill, how often did you leave your apartment or house?" Choices are: never; 3-4 times a week; daily; multiple times per day.  Seems like we need another option between "never" and "3-4 times a week"

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Hayley is referring to Q13 - Q15 on Survey 2 (COVID recent Experience.) 


And Q.14 on Survey 4. Waiting on Wendy for these design proposals.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Please update Survey 2, Q13-Q15 to have these updates:

![Screen Shot 2020-06-01 at 3 14 02 PM](https://user-images.githubusercontent.com/64874011/83460130-883c9c80-a41a-11ea-85f1-9917ea627ac1.png)




Please update Survey 4's Q. 14 to have these options:

![Screen Shot 2020-06-01 at 3 12 50 PM](https://user-images.githubusercontent.com/64874011/83460044-5cb9b200-a41a-11ea-8390-d9b62a05c595.png)

Thanks!
