### ISSUE TITLE
Add a survey question "How did you hear about this study?"

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#453]
Wendy is still drafting content for this, will update when we have the responses.

Probably makes sense to put this in Survey 2.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@mkellen  - I confirmed with Wendy that Survey 1 is about "Tell us about yourself" and Survey 2 is about "Recent COVID experience" and she mentioned Survey 1 then. 
The updated question is below.

I think it makes sense to add this as the last question to Survey 1: 

Questions: 
How did you hear about this study?
(Check all that apply) 

Newspaper
Radio
Television
Facebook
Twitter
Online search
Flier/poster
Recruit Me website
Email from Columbia University
Allianca Dominicana
Survivor Corps
Friend/family
Other: __________
