### ISSUE TITLE
Date validation lacking on symptom history - Survey 2

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#455]
Questions 1-4 ask for a series of dates from the participant. It does not make sense for these dates to not occur in chronological order - e.g. the answer to question 1 logically should be the first date, 2 should be the second. Currently the UI just allows these responses to occur in any order.

It would be an improvement if the UI forced the dates to occur in chronological order. Ideally, the UI should let people know if they enter something out of order because the error could just as easily be the date entered on a prior question.

A related issue is while the UI does do a validation check to prevent the user from entering dates in the future, it silently defaults to today's date if a date in the future is entered. This isn't ideal because the user may have made some other sort of error in which this isn't what the user intended. 

A better UI would be a date picker, in which dates in the future were disabled. In addition, for questions 2-4, dates earlier than the previous question's answer should be disabled. Lynn may have other design approaches to collecting this data, and realize we are pretty limited in time at this point so we might not end up with an ideal solution.

**Comment by mkellen** [comment]
OK, realized that this validation check does happen, it just doesn't happen until the page is submitted.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@mkellen  I agree with Mike's comments above. Please ping me for any constraints, and we can figure it out from there.

**Comment by conundrumgirl** [comment]
@mkellen @flylikeabirdfloatlikeabuoy  since validation does indeed happen is it still an issue or can we close?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-06-02 at 2 03 53 PM](https://user-images.githubusercontent.com/64874011/83569793-e5e3ee00-a4d9-11ea-917e-9ef57c6ff9df.png)

Is it too expensive to implement the above suggestion?  Otherwise it is fine. I added screen shot and noticed that Q4. of that survey 2 has "2019" as a drop down option. 

Thanks

**Comment by conundrumgirl** [comment]
I will take care of 2019. As far as implementing the datepicker - yes it is quite expensive.
We would need to  find a third party date picker and figure out how to integrate that and the date validation in the forms framework and then reimplement those questions.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Then what we have is fine ;)

**Comment by conundrumgirl** [comment]
Removed 2019. The rest I guess is OK?
