### ISSUE TITLE
The clear button breaks the page: Survey 2, questions 3 and 4

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#457]
Pressing the clear button on survey 2, questions 3 and 4 leads to loading a completely blank page. Only way out I could find was back button on browser, taking me to the dashboard. Then reloading the survey worked but lost my prior state.

**Comment by conundrumgirl** [comment]
@mkellen, thanks for the great catch! Broke this yesterday while trying to fix somethings else.
Fixed now. Can you please verify?
