### ISSUE TITLE
Should the dashboard look different if all surveys have been completed?

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#465]
After completing all the surveys, the dashboard is a page in which there's instructions on completing the surveys, and all the surveys are checked off.

It seems some sort of "Thank You" page would be better, where we clearly tell people there's nothing left for them to do. We might want to indicate that follow up surveys may come out at a later date.

We might also want to tell people they're on the waiting list for serology testing, and will be notified if they've been selected.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Really great suggestion, don't how I missed this. Been in it too deep I guess. Let me mock something. 

Thanks

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Worked through this with Vanessa and we think it's really two screens, one after they've submitted minimum surveys, and the second one where It's all of them.
If finished 3 minimum:

[Header text]
Whoo hoo!

[Body] 
We’ve added you to the waiting list for an antibody test. If you are selected, you will receive an email.

Please consider completing the rest of the surveys if you have time. 

When they complete all of the surveys, they see this screen:

[Header text]
Thank you for your contribution to the COVID Recovery Corps Study! 


![Screen Shot 2020-06-02 at 5 51 13 PM](https://user-images.githubusercontent.com/64874011/83583617-a7f6c200-a4f9-11ea-9a9a-89e38d61f694.png)

**Comment by mkellen** [comment]
Yes, this is nice
