### ISSUE TITLE
Add response to race question to Participant Manager

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#482]
Need to include this so Columbia can manage the demographics of who they invite for blood draws

**Comment by jay-hodgson** [comment]
In addition to ethnicity, we also want to filter on sex, age, and zip code.

**Comment by conundrumgirl** [comment]
@mkellen @jay-hodgson  - who does this need to be assigned to?

**Comment by jay-hodgson** [comment]
This should be done!
