### ISSUE TITLE
Give people the option to volunteer for blood draws or wait for home testing

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#483]
On the page where people qualify for blood draw testing (successful completion of Survey 2) - we should ask them if they want to volunteer immediately for blood draw, or if they'd prefer to be on the waiting list for a home test kit. 

Key things to convey:

- We can't guarantee a spot just because they volunteer - both spots are limited to availability
- Home test kits are at least a month out, possibly several months out
- May want to convey benefits / drawback of each approach

Assigning to Lynn to work on design - please coordinate with Vanessa on language.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-06-10 at 4 55 32 PM](https://user-images.githubusercontent.com/64874011/84330055-3511ca80-ab3b-11ea-99d1-9f0c5600a94c.png)

[same check mark logo as other page]
Whoo hoo!

You’ve completed the minimum surveys to qualify for an antibody test! 

Although we cannot guarantee testing for everyone, we will do our best to accomodate based on availability. 

[bold text]
Would you prefer to go to a lab draw or wait until home test kits are available? 
 
If they click either lab draw or home test kit:

[same check mark icon]

Thank you!

We’ve added you to the waiting list for an antibody test. If you are selected, you will receive an email.

Please consider completing the rest of the surveys if you have time.



if they opted out of testing entirely:

[same check mark icon]

Thank you!
Please consider completing the rest of the surveys if you have time.
