### ISSUE TITLE
Copy pending from CZI

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#49]
Waiting for CZI to update copy for a lot of placeholder text: 

+ Update text for "X" canceling consent or disagreeing
+ Dashboard experience for first time log in "Yay legal work..."
+Ineligibility message prompt and joining the mailing list
+ Copy for Email Login Experience

**Comment by jay-hodgson** [comment]
@flylikeabirdfloatlikeabuoy : Can this be closed (have these already been updated in the design and implementation)?
