### ISSUE TITLE
Photos and text in header

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#496]
Please change photos to the following:

(first photo) https://www.gettyimages.com/detail/news-photo/food-is-distributed-at-common-pantry-in-harlem-on-april-20-news-photo/1219998495?adppopup=true

https://www.gettyimages.com/detail/news-photo/sevonna-brown-of-black-womens-blueprint-a-mutual-aid-group-news-photo/1212730608?adppopup=true

Let's keep the older couple on zoom and the biker.

Please change text to the following:

A community-powered movement
to understand COVID-19 across NYC.

**Comment by hayleybr00ks** [comment]
[
![GettyImages-1207986263](https://user-images.githubusercontent.com/47126880/84184073-9eadae00-aa41-11ea-8f40-50d993986ddb.jpg)
![Uploading GettyImages-1219998495.jpg…]()

](url)

**Comment by hayleybr00ks** [comment]
![GettyImages-1212730608](https://user-images.githubusercontent.com/47126880/84184090-a705e900-aa41-11ea-9385-50b7c7c55227.jpg)

**Comment by hayleybr00ks** [comment]
![GettyImages-1219998495](https://user-images.githubusercontent.com/47126880/84184435-2f848980-aa42-11ea-9bfb-ef9652289327.jpg)

**Comment by hayleybr00ks** [comment]
Just noticing we still need to update text - A community-powered movement
to understand COVID-19 across NYC.

**Comment by conundrumgirl** [comment]
fixed both issues
