### ISSUE TITLE
Top nav needs to collapse gracefully into hamburger menu in mobile

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#51]
Top nav needs to collapse gracefully into hamburger menu in mobile

Please refer to Figma for mockup on how to handle sliding tray when the hamburger icon is selected in mobile

**Comment by jay-hodgson** [comment]
@flylikeabirdfloatlikeabuoy : Could you copy a screenshot of the relevant part of the design into the issue?  I'm sure what you're talking about is somewhere in here, but we don't know this file like you do!
<img width="680" alt="Screen Shot 2020-05-07 at 11 03 46 AM" src="https://user-images.githubusercontent.com/1864447/81328952-9d5c2080-9052-11ea-9510-93ae3ca749e1.png">

**Comment by jay-hodgson** [comment]
Right now I understand this as issue as "on hamburger menu item click, the menu should collapse".  Is that inaccurate?

**Comment by jay-hodgson** [comment]
If my interpretation is correct, then this was also fixed.
