### ISSUE TITLE
Error codes for required sections need to be clear

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#52]
Error code treatment needs to be more clear 

+ move summary of errors from top of page to bottom near submit button (because wont be visible in long list - see Figma mockup

+ schedule time with Lynn to communicate constraints on what can be done easier than what's currently in Figma

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy , per our conversation I'm removing the summary (i turn it on occasionally for debugging purposes but it will not be in the final product)
