### ISSUE TITLE
Header photos on mobile look different

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#521]
Screenshots below. Notice the grey bar under header text / join us button changes depending on the photo. Any way to standardize? Thanks!

**Comment by hayleybr00ks** [comment]
![103850594_1666487683489113_8188576480664991128_n](https://user-images.githubusercontent.com/47126880/84533073-445c5980-ac9c-11ea-91cd-94dfccbda00d.jpg)

**Comment by hayleybr00ks** [comment]
![83775986_880595229109293_2970718682476728032_n](https://user-images.githubusercontent.com/47126880/84533086-4a523a80-ac9c-11ea-8c33-61936284e415.jpg)

**Comment by hayleybr00ks** [comment]
![103954450_712697582850320_5889573400022572447_n](https://user-images.githubusercontent.com/47126880/84533098-50481b80-ac9c-11ea-9d18-a6dcb73e203d.jpg)

**Comment by conundrumgirl** [comment]
@hayleybr00ks @flylikeabirdfloatlikeabuoy -re-cropped  the mobile photos please verify

**Comment by hayleybr00ks** [comment]
these look so good, thank you so much!! @conundrumgirl
