### ISSUE TITLE
URGENT!!  error statement persists after going back to survey dashboard (see comments) 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#528]
1. Currently if user exits consent, clicks "start consent" or  "survey dashboard" they see this:  
<img width="925" alt="Screen Shot 2020-06-15 at 4 10 58 PM" src="https://user-images.githubusercontent.com/64874011/84714657-2ce2d200-af23-11ea-9b54-91342bb6aac6.png">

2.  Not sure if participant should see "Account Settings" if they haven't signed consent

<img width="925" alt="Screen Shot 2020-06-15 at 4 11 56 PM" src="https://user-images.githubusercontent.com/64874011/84714625-150b4e00-af23-11ea-8b04-6620a2140751.png">

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy, what is the exact sequence of steps that you did to get here?
Was it a new user?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Per our conversation - 

1. Pink error statement should not show during the consent experience.
2. We will no longer show "Survey Dashboard and Account Settings" for a new user who has NOT consented because the officially don't have an account. 

Thanks, Alina!
