### ISSUE TITLE
Buttons and responses should not be in all caps

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#54]
Buttons should not be in all caps -- 
Same with answers or any response input

SUBMIT ---> Submit

**Comment by jay-hodgson** [comment]
Button text transform is an easy fix.  Could you point me to an example of an "answer" or a "response input" that suffers from this issue?

**Comment by jay-hodgson** [comment]
This might be fixed (if they are all buttons).
