### ISSUE TITLE
For quizzes change the styles for wrong/right answer

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#55]

**Comment by jay-hodgson** [comment]
Need style update examples.  @flylikeabirdfloatlikeabuoy, could you attach screenshots (or point me to the right area in the figma file)?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-12 at 2 21 01 PM](https://user-images.githubusercontent.com/64874011/81746718-cff38800-945b-11ea-88bd-9b815a5a484d.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-12 at 2 21 18 PM](https://user-images.githubusercontent.com/64874011/81746758-daae1d00-945b-11ea-876d-728e25d5a746.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-12 at 3 03 25 PM](https://user-images.githubusercontent.com/64874011/81750090-bbb28980-9461-11ea-96ba-1ea8badaf010.png)

**Comment by jay-hodgson** [comment]
Closer: 
<img width="476" alt="Screen Shot 2020-05-12 at 3 59 34 PM" src="https://user-images.githubusercontent.com/1864447/81753892-a8a3b780-9469-11ea-8eb3-026a1476c544.png">
<img width="479" alt="Screen Shot 2020-05-12 at 3 59 26 PM" src="https://user-images.githubusercontent.com/1864447/81753896-a93c4e00-9469-11ea-9e1c-84a31d5fe7c3.png">
