### ISSUE TITLE
Account settings - HIPAA Auth

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#559]
I had already signed the HIPAA authorization when I went into account settings and turned off the option to share these records. When I turn it back on, I'm asked to go through the HIPAA auth consent process again. Do we need new consent from someone every time if they change their mind? Screenshots attached
<img width="582" alt="Screen Shot 2020-06-23 at 10 34 53 AM" src="https://user-images.githubusercontent.com/47126880/85436456-f23df280-b53d-11ea-9202-012041bb9912.png">
<img width="661" alt="Screen Shot 2020-06-23 at 10 38 59 AM" src="https://user-images.githubusercontent.com/47126880/85436470-f702a680-b53d-11ea-89db-0d10fac5350c.png">

**Comment by conundrumgirl** [comment]
@hayleybr00ks , per @vbarone00 " if they decide later to give ehr access they should be forced to do the HIPAA consent". So I think this works as designed. Thank you for covering the edge cases !
