### ISSUE TITLE
"Summary/Fulltext toggle" UI improvements

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#56]
Adjust size of text and toggle of "Summary vs. Fulltext" 
text size: 16pt 
Should be on **summary** on default instead of full text

**Comment by jay-hodgson** [comment]
16pt seemed far too large on my device:
<img width="495" alt="Screen Shot 2020-05-08 at 12 43 12 PM" src="https://user-images.githubusercontent.com/1864447/81443274-fea2f300-9129-11ea-82f4-312686486f13.png">

Changed to 1.5rem to be closer to design mocks:
<img width="496" alt="Screen Shot 2020-05-08 at 12 42 06 PM" src="https://user-images.githubusercontent.com/1864447/81443304-0b274b80-912a-11ea-9bda-9e8d1b4a5092.png">
