### ISSUE TITLE
Address validation with incorrect state

### ISSUE THREAD

**Issue by conundrumgirl** [Sage-Bionetworks/covidrecoverycorps#561]
entering this address
![image](https://user-images.githubusercontent.com/5190623/85441936-7c895500-b544-11ea-89f3-af5cc1cacd1b.png)

Is a valid Seattle WA address but the state is NY. The API is smart enough to figure out and correct that address returning the valid address  but it does not get updated.

I wonder if we need to always update the address with what gets returned from the API when it's deemed correct

![image](https://user-images.githubusercontent.com/5190623/85442232-ca05c200-b544-11ea-8ec6-10ebd40736e1.png)

<Address2>5750 E GREEN LAKE WAY N</Address2><City>SEATTLE</City><State>WA</State><Zip5>98103</Zip5><Zip4>5954</Zip4></Address></AddressValidateResponse>

ake%20Way%20North%3C/Address1%3E%3CAddress2%3Eapt%20001%3C/Address2%3E%0A%20%20%20%20%3CCity%3ESeattle%3C/City%3E%3CState%3ENY%3C/State%3E%3CZip5%3E98103%3C/Zip5%3E%3CZip4%3E%3C/Zip4%3E%3C/Address%3E%3C/AddressValidateRequest%3E

![image](https://user-images.githubusercontent.com/5190623/85444511-400b2880-b547-11ea-84a5-ad9074e4caf8.png)

**Comment by jay-hodgson** [comment]
Ahh, the code I have is to guard against this situation for the zip code and city, but not the state!

**Comment by jay-hodgson** [comment]
I've been taking the approach that we do not modify the user-entered data in the usps validation check (I'd hate to introduce a mistake into the data!).  Instead, we just block if any of these situations is detected by the validation test.

**Comment by jay-hodgson** [comment]
Thank you for finding this @conundrumgirl !!!

**Comment by conundrumgirl** [comment]
> I've been taking the approach that we do not modify the user-entered data in the usps validation check (I'd hate to introduce a mistake into the data!). Instead, we just block if any of these situations is detected by the validation test.

What I am noticing that it's possible that there are discrepancies with valid addresses. e.g.
https://www.zillow.com/homedetails/35-45-79th-St-5E-Jackson-Heights-NY-11372/2079033914_zpid/
The city of Jackson Heights gets returned as `<City>JACKSON HTS</City>` so you get an error if you try to enter the address

**Comment by jay-hodgson** [comment]
Proposing the following change to the error (to expose the expected value):

> Sorry, the `field` entered does not correspond to a valid mailing address. Did you mean '`expected value`'?

**Comment by jay-hodgson** [comment]
In the case above, it would show
Sorry, the city entered does not correspond to a valid mailing address. Did you mean 'JACKSON HTS'?
