### ISSUE TITLE
Consent - Add new screen to econsent

### ISSUE THREAD

**Issue by vbarone00** [Sage-Bionetworks/covidrecoverycorps#574]
We need to add a new screen to the consent: 

Screen 8: Will I receive any form of compensation for participating in the study?
Summary:
You will be given $50 gift card if you complete all of the surveys and provide biosamples in
person they provide samples in person or a $20 gift card if you provide biosamples from home.
You will not receive any profit from this or future research.

Full Text:
You will be given $50 gift card if you complete all of the surveys and provide biosamples in
person they provide samples in person or a $20 gift card if you provide biosamples from home.
Researchers will use your data to make discoveries. If any of their studies lead to new tests,
drugs, or other commercial products, you will not get any profits. These inventions will be the
property of the researchers who develop them.

 The previous screen #8: Leaving the study will now become  #9: Leaving the study

**Comment by conundrumgirl** [comment]
Will probably need top graphics  for this @flylikeabirdfloatlikeabuoy

**Comment by flylikeabirdfloatlikeabuoy** [comment]
I've reached out to our external group. will post here once available. Thanks!

**Comment by flylikeabirdfloatlikeabuoy** [comment]
I recommend placing it on screen 9 (Before this is Not Medicare)  rather than 8.  
Here is the transparent .png: 

![09 giftCard](https://user-images.githubusercontent.com/64874011/86063520-e95a8e80-ba1f-11ea-9f8b-7ee85ae5ef4c.png)

**Comment by vbarone00** [comment]
You will be given a $50 gift card if you complete all of the surveys and provide biosamples in
person. If you complete all your surveys and provide a biosample with an at-home kit  will receive a $20 gift card.
