### ISSUE TITLE
Urgent: Moving First/Last name into Survey 1 from sign up experience

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#63]
![image](https://user-images.githubusercontent.com/64874011/81341624-b79ff980-9066-11ea-953c-b247b9fcdc66.png)

Due to potential security concern of sending welcome login verification to wrong user, we are moving the “What is your full name” into Survey 1 as oppose to the initial sign up experience. 

Consent and EHR will remain the same. 

Survey 1 will now have: First/Last name, DOB, Address, Gender.

**Comment by conundrumgirl** [comment]
Done.
