### ISSUE TITLE
Return of results page improvements

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#649]
1. Add invite a friend reusing Share functionality from the home page
2. Add section with technical information about the test
3. Handle the post-lab surveys
4. Can have text about newsletter with study findings, but no switch to manage subscriptions. Users will be automatically put on Columbia's list-serve and they can unsubscribe from there if not interested.
5. Remove all content related to serum collection

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@conundrumgirl  Please see: 

<img width="270" alt="Screen Shot 2020-08-11 at 11 39 12 AM" src="https://user-images.githubusercontent.com/64874011/89935610-4a50b700-dbc7-11ea-88eb-8ff0e78899e5.png">
