### ISSUE TITLE
Learning Hub - static content

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#651]

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Please see figma page for latest text and imagery. 

<img width="314" alt="Screen Shot 2020-08-11 at 11 36 07 AM" src="https://user-images.githubusercontent.com/64874011/89935329-dadac780-dbc6-11ea-954a-e0b71207a0fc.png">
