### ISSUE TITLE
Dashboard for tracking progress

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#653]
Dear Mike,

 

We’ve been thinking about the best way to monitor activity on the website to be able to focus the recruitment efforts and progress through the study modules.

 

Going through the registration process a few times, we think these points will provide the critical metrics of recruitment/progress:

 

Participant created an account
Participant signed informed consent
Participant answered electronic health record question
Participant completed survey 1
Participant completed survey 2
Participant completed survey 3
Participant completed survey 4
Participant provided employer information
 

We were hoping to be able to obtain these numbers so we can manage the study better.  This could either be an administrative portal or report pushed out regularly.

 

Please let me know how we can best do this?

 

Kind regards, Todor

**Comment by mkellen** [comment]
On call, we agreed to not track account creation, just start with people after they're consented for simplicity

**Comment by jay-hodgson** [comment]
If we implemented the recent Facebook Pixel ask (unique urls for each step, including a url that the user would be sent to after all surveys are complete), would this be solved?

@conundrumgirl @flylikeabirdfloatlikeabuoy

**Comment by conundrumgirl** [comment]
@jay-hodgson - we do have a separate /done page for the surveys 1-4 so it is easy to attach a query param to the url that identifies the survey. I think this should fulfill the survey requirement.
'Participant provided employer information' - this is something done on the Columbia side when scheduling an appointment

Participant signed informed consent - this is a component - we can may be make it page?
Participant answered electronic health record question - Starting Consent EHR is a link -- can we hook into that?

I need to investigate of pixel supports events or if pushing to history would update the data sent.

**Comment by jay-hodgson** [comment]
> I need to investigate of pixel supports events or if pushing to history would update the data sent.

I was thinking the same thing.  If we sent events to indicate state (signed informed consent, answered EHR question, completed all surveys), then perhaps we don't need unique URLs.

**Comment by conundrumgirl** [comment]
Looks like events are supported 
https://developers.facebook.com/docs/facebook-pixel/implementation/conversion-tracking/

**Comment by jay-hodgson** [comment]
I was conflating this with #672 , now tracking as a separate issue.

This issue is to add 2 new charts to the Participant Manager:
1. New participant counts per day based on steps completed (line chart).
2. Overview of surveys completed out of total accounts (donut charts).

Not sure how the first chart will be built yet.
The second chart will be built using @itismeghasyam 's [summary table](https://www.synapse.org/#!Synapse:syn22311184/tables/).

**Comment by jay-hodgson** [comment]
The set of charts to show the overview of surveys completed (out of total accounts) is now on the [staging crc researcher portal](https://staging.covidrecoverycorpsresearcher.synapse.org/).

**Comment by jay-hodgson** [comment]
This is what we have today (from https://github.com/Sage-Bionetworks/portals/pull/377):
<img width="906" alt="Screen Shot 2020-08-24 at 9 54 15 AM" src="https://user-images.githubusercontent.com/1864447/91073627-33ab5680-e5f0-11ea-95a9-d2c886ceb12f.png">

To add additional data to the plot, please make it available in syn22314856 table (then we just need to update the sql in the portal).
