### ISSUE TITLE
Message to participants that at home testing is not likely to be available for a few months

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#660]
Coordinate with Wendy on exact language

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Per Wendy's approval, please update body text to be: 

"To receive a gift card, you will need to be invited to an antibody test and provide a biosample.

We cannot guarantee testing invites for all participants at this time. 

Please note that at-home test kits won’t be available until after December 2020. " 

<img width="231" alt="Screen Shot 2020-08-13 at 9 54 40 AM" src="https://user-images.githubusercontent.com/64874011/90163482-02f33380-dd4b-11ea-8a43-a55d6ff79d4a.png">
