### ISSUE TITLE
Ask set of users who selected home kit if that is still their choice

### ISSUE THREAD

**Issue by jay-hodgson** [Sage-Bionetworks/covidrecoverycorps#661]
Since home testing is not likely to be available for a few months.  One option is to essentially delete the home/lab selection choice for these users, and notify users in an email to reaffirm their selection (with a link to this survey).
Another option might be to send these emails to Columbia for them to work out who wants a lab test, and then we  let them know the health codes to consider for lab testing (overriding the survey) in the Participant Manager.

**Comment by jay-hodgson** [comment]
To see participants who selected 'home' test location, they can click [here](https://staging.covidrecoverycorpsresearcher.synapse.org/Explore/1.%20Uncategorized?QueryWrapper0=%7B%22sql%22%3A%22SELECT%20symptom%2C%20%5Cn%20%20%20%20firstDayOfSymptoms%2C%20%5Cn%20%20%20%20lastDayOfSymptoms%2C%5Cn%20%20%20%20worstDayOfSymptoms%2C%5Cn%20%20%20%20dontFeelBetter%2C%5Cn%20%20%20%20recoveryDateOfSymptoms%2C%5Cn%20%20%20%20stillHaveSymptoms%2C%5Cn%20%20%20%20testType%2C%5Cn%20%20%20%20feverHighest%2C%20%5Cn%20%20%20%20otherSpecify%2C%20%5Cn%20%20%20%20howWasItTreated%2C%20%5Cn%20%20%20%20gender%2C%20%5Cn%20%20%20%20age%2C%20%5Cn%20%20%20%20ethnicity%2C%20%5Cn%20%20%20%20zipcode%2C%20%5Cn%20%20%20%20nasalSwabDate%2C%20%5Cn%20%20%20%20nasalSwabResult%2C%20%5Cn%20%20%20%20serumTestDate%2C%20%5Cn%20%20%20%20serumTestResult%2C%20%5Cn%20%20%20%20uploadDate%2C%5Cn%20%20%20%20healthCode%2C%5Cn%20%20%20%20recordId%2C%5Cn%20%20%20%20testLocation%2C%5Cn%20%20%20%20dataGroups%20%20FROM%20syn22154087%20%20%20WHERE%20testLocation%20IN%20(%27lab%27%2C%20%27home%27%2C%20%27noTest%27)%20AND%20dataGroups%20NOT%20HAS%20(%27test_user%27)%20AND%20uploadDate%20%3E%201595808000000%20AND%20WorkflowState%20%3D%20%20%20%20%27Uncategorized%27%22%2C%22limit%22%3A25%2C%22offset%22%3A0%2C%22selectedFacets%22%3A%5B%7B%22concreteType%22%3A%22org.sagebionetworks.repo.model.table.FacetColumnValuesRequest%22%2C%22columnName%22%3A%22testLocation%22%2C%22facetValues%22%3A%5B%22home%22%5D%7D%5D%2C%22sort%22%3A%5B%7B%22column%22%3A%22uploadDate%22%2C%22direction%22%3A%22ASC%22%7D%5D%7D).
Note that this is sorted by uploadDate (desc), so researchers should send us the health codes for individuals they'd like to select up to the cutoff date (what is that date?).

**Comment by conundrumgirl** [comment]
Just a note for what the plan is:

- make a list of healthCodes and email addresses of everyone who selected 'home' up to the [date determined at the meeting/today] 
- send Columbia email addresses of those people
- get from Columbia a list of healthCodes of people who selected 'home' and who they want to invite
- get from Columbia list of email addresses of people who responded to change their preference
- if the email address matches healthCode for invite -- invite via participant manager

**Comment by conundrumgirl** [comment]
I will intive the participants who choose 'lab' as I get the emails from Columbia. For now we have 6 people that have been invited. I'm going to close it
