### ISSUE TITLE
Spanish email when signed in from spanish site

### ISSUE THREAD

**Issue by conundrumgirl** [Sage-Bionetworks/covidrecoverycorps#669]
When the user logs in from the spanish version we need to send them an appropriate email.
I'm sending 'es' in 'Accept-Language' header.
Spanish translation: 
Subject:
Inicie sesión en la cuenta - COVID Recovery Corps 

¡Hola!
Por favor haga clic en el enlace ubicado subsiguiente para acceder a su cuenta.
Iniciar sesión
Si usted tiene alguna pregunta o necesita ayuda, puede llamar al 202-305-5700 o enviar un correo electrónico a COVIDRecoveryCorps@cumc.columbia.edu 

![image](https://user-images.githubusercontent.com/5190623/90446495-57254d00-e096-11ea-8944-39df771d48fa.png)

**Comment by alxdarksage** [comment]
Added to app configuration.
