### ISSUE TITLE
Facebook tracking of CRC adds

### ISSUE THREAD

**Issue by jay-hodgson** [Sage-Bionetworks/covidrecoverycorps#672]
The request is to reorder the site so there is a Unique URL for the "study completed" page when somebody completes all the surveys.  Can we instead send a custom FB Pixel event from the dashboard?

@mkellen

**Comment by jay-hodgson** [comment]
@conundrumgirl points out that we need access to the FB Pixel admin dashboard to see if custom events are working.

**Comment by conundrumgirl** [comment]
@mkellen @jay-hodgson from the discussion in yesterday's meeting it's likely sufficient to add a query param to /done page that we redirect to after surveys 1-4 get completed. I will make this change in the code and reach out to Rodolfo to confirm

**Comment by conundrumgirl** [comment]
added 
/done?surveyname=COVID_EXPERIENCE
/done?surveyname=DEMOGRAPHIC
/done?surveyname=HISTORY
/done?surveyname=MORE

Got confirmation from Rodolfo that it is sufficient
