### ISSUE TITLE
Participant Manager not showing updates when scheduling occurs

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#680]
Participant manager status is updated when people are invited, but not when they are scheduled or results are ready.

We should be getting callbacks from Columbia's system and think we are because we previously validated that the participant portal updated based on these events.

Raised by Todor on today's call.

**Comment by alxdarksage** [comment]
In the last 3 days:

8/26 - procedurerequest was posted with a 201 and the report is there
request id: YfR3mz8fNagNYf4mB8dGJYOx

There are many 7 observations filed in the last three days, all successful.

**Comment by alxdarksage** [comment]
I can confirm that we have 6 reports filed, and all are marked as test_available. There's one account that has an observation that is marked tests_scheduled, which is not expected, but it's also a test account and may have been reused. So, I see callbacks from Columbia, but not as many procedurerequests as final lab reports.I see no errors to these calls.

**Comment by alxdarksage** [comment]
There have been 8 callbacks in the last 3 days, all successful, and there have been no errors logged.

**Comment by itismeghasyam** [comment]
[Participant viewer table](https://www.synapse.org/#!Synapse:syn22154087/tables/) now has two more updates to the _WorkflowState_ column
1. **Scheduled**:
We move the record to this state if we can find a non-NA/non-NULL value for the _scheduledLabDrawOn_ column 

2. **Results Ready**:
The _dataGroups_ column of the [Default Health Data Record Table](https://www.synapse.org/#!Synapse:syn22028237/tables/) is updated to show if a healthCode has completed tests. We pull this _dataGroups_ for each healthCode, and see if we find atleast once the markers for completed tests (i.e the _dataGroups_ have the strings - 'tests_available', 'tests_available_type_unknown'). The _WorkflowState_ column of the corresponding rows in the [Participant viewer table](https://www.synapse.org/#!Synapse:syn22154087/tables/) is updated accordingly

**Comment by conundrumgirl** [comment]
@itismeghasyam has completed this
