### ISSUE TITLE
Remove this image from the homepage

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#685]
Hi there! We received some less than positive feedback on one of the images on the homepage. Can you remove this one from the rotating header images and let me know when it is removed? Thanks!

Hayley

<img width="1354" alt="Screen Shot 2020-09-03 at 7 22 38 AM" src="https://user-images.githubusercontent.com/47126880/92127538-43782700-edb6-11ea-889d-a7ba93498769.png">

**Comment by conundrumgirl** [comment]
Updated the image w/ the one with the mask on
