### ISSUE TITLE
NATIONWIDE: updated text string from Hayley

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#692]
@hayleybr00ks

+ New text string for "About" aka home page of CRC 
+ top paragraph under "Meet the Researcher" 
+ scan for any other NYC specific text that needs to be updated

**Comment by hayleybr00ks** [comment]
Hi @flylikeabirdfloatlikeabuoy here you go. I think we can leave the part about how we started in NYC, but defer to Wendy on final edits/version. 
[4.CRC_Appendix E _ Study Website Copy_v2.0_18.June2020_HBedits.docx](https://github.com/Sage-Bionetworks/covidrecoverycorps/files/5211530/4.CRC_Appendix.E._.Study.Website.Copy_v2.0_18.June2020_HBedits.docx)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@conundrumgirl  Wendy & co is reviewing this. Once this is set - I'll update the mockup and post here

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy , can this be closed?
