### ISSUE TITLE
NATIONWIDE: Please update the thank you screen to be more generic to work for both nationwide and 25 miles

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#697]
Please update text to say, "If you are selected to receive an antibody test,  you will receive an email." 
Remove previous text about waitlist. 

<img width="862" alt="Screen Shot 2020-09-09 at 1 51 07 PM" src="https://user-images.githubusercontent.com/64874011/92653661-85680800-f2a3-11ea-9e06-0f13edfd595d.png">

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy , right now we have 2 versions of thank you screen:
If they selected 'no test' they see this:
![image](https://user-images.githubusercontent.com/5190623/92976793-3d321c80-f440-11ea-85f1-e773121f25e5.png)

If they selected home or lab they see this:


![image](https://user-images.githubusercontent.com/5190623/92976877-7074ab80-f440-11ea-938e-55aa61986d2e.png)


Do you want me to change both versions to be as above or only the one for the home and lab test?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@conundrumgirl  Please keep the no test Thank you unchanged. Only apply it to the home and lab test. 

Thanks!
