### ISSUE TITLE
UPDATED NATIONWIDE: Within 25 mile radius testing selection

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#708]
If a participant has self selected that they are positive for COVID-19 from a PCR/Serology test, we will no longer invite them for any type of testing. 

If a participant is within 25 mile radius of the Columbia Medical Center and have not tested positive for PCR or Serology test, they will see this screen to select how they want their antibody test to be conducted:

<img width="271" alt="Screen Shot 2020-11-09 at 3 04 16 PM" src="https://user-images.githubusercontent.com/64874011/98606860-d775db80-229c-11eb-80f8-466965711991.png">

If they selected: Lab test:
<img width="274" alt="Screen Shot 2020-11-09 at 3 05 57 PM" src="https://user-images.githubusercontent.com/64874011/98606985-1441d280-229d-11eb-9f53-df8724f444c9.png">

If they selected at home test kit:
If they said no, we will link them to update their Contact Information 
<img width="935" alt="Screen Shot 2020-11-09 at 3 06 55 PM" src="https://user-images.githubusercontent.com/64874011/98607053-376c8200-229d-11eb-9c0e-2934f6f777bc.png">

@vbarone00  Please  have a final pass of the language

**Comment by vbarone00** [comment]
Looks good! No edits from me!

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Waiting on Wendy's additional copy @conundrumgirl

**Comment by conundrumgirl** [comment]
I am closing this since we don't offer lab testing any more <25 miles has no relevance.
