### ISSUE TITLE
UPDATED NATIONWIDE: Outside of 25 mile radius 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#709]
If participant is OUTSIDE of the 25 mile AND have NOT tested positive for COVID-19, they will see this: 

<img width="263" alt="Screen Shot 2020-11-09 at 3 11 47 PM" src="https://user-images.githubusercontent.com/64874011/98607371-e446ff00-229d-11eb-98bd-86f91ad35ebd.png">

If they said Yes to At home test kit:
We will direct them to update their contact information if the address isn't correct
<img width="939" alt="Screen Shot 2020-11-09 at 3 12 15 PM" src="https://user-images.githubusercontent.com/64874011/98607404-f4f77500-229d-11eb-8040-9a70f794afe6.png">

@vbarone00  Please check final copy between this and issue #708  

Thanks

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Waiting on Wendy's additional copy @conundrumgirl

**Comment by conundrumgirl** [comment]
https://docs.google.com/presentation/d/1cI7fCSjWagy9roCzsDnlLZJQfPq6vl5nlWPCUpqgVbo/edit#slide=id.gaf1f78aded_0_18

The updated design is here
