### ISSUE TITLE
BUG: FAQ Section of Learning Hub is missing. Check with Wendy for any updated Q and A

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#718]
<img width="1583" alt="Screen Shot 2020-11-20 at 2 57 46 PM" src="https://user-images.githubusercontent.com/64874011/99857732-c3559800-2b40-11eb-9e63-0249fb7340a2.png">
<img width="863" alt="Screen Shot 2020-11-20 at 2 58 45 PM" src="https://user-images.githubusercontent.com/64874011/99857793-e4b68400-2b40-11eb-911d-4a75b3aff294.png">

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy  - I am not seeing this. Can you please deublecheck?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Yeah Im' still seeing it on staging. @conundrumgirl

**Comment by conundrumgirl** [comment]
Has been fixed and verified by Lynn
