### ISSUE TITLE
Bug! visual of toggle in black consent bar is not visible: please update to be: 807C7C for ellipse 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#720]
Currently top bar of Summary vs. Full text looks like this:

![image](https://user-images.githubusercontent.com/64874011/100922994-67213b00-3493-11eb-9565-3316db21958f.png)

Should look like this:
<img width="564" alt="Screen Shot 2020-12-02 at 11 41 28 AM" src="https://user-images.githubusercontent.com/64874011/100922934-51ac1100-3493-11eb-9f89-653c3d6ab82f.png">

**Comment by conundrumgirl** [comment]
![image](https://user-images.githubusercontent.com/5190623/101395016-2f910500-387e-11eb-8b1b-950298afabe1.png)
