### ISSUE TITLE
!! Nationwide launch: additional public page that is unlinked

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#732]
For the home kit paper instruction, we have a QR on the top right that will be mapping to a video instruction both in English and Spanish from Columbia on how to collect the blood sample.  

<img width="934" alt="Screen Shot 2021-01-12 at 11 14 15 AM" src="https://user-images.githubusercontent.com/64874011/104361467-566ad880-54c7-11eb-9ce8-42ffb329836d.png">

Please create a public page (no login requirement) with the following URL: 

https://covidrecoverycorps.org/testkit

English Instructions: 

https://youtu.be/--MX5u9a12Y

Spanish instructions: 
https://youtu.be/bM6MoVTAegQ

**Comment by flylikeabirdfloatlikeabuoy** [comment]
The QR code will map to:

/testkit. 

There will be a button that toggles between English and Spanish instructions: 

<img width="737" alt="Screen Shot 2021-01-12 at 11 43 55 AM" src="https://user-images.githubusercontent.com/64874011/104364459-756b6980-54cb-11eb-97f0-753a32b8ce59.png">

**Comment by conundrumgirl** [comment]
@leonli33 - there are several tasks: 
 - create a new page at a path /testkit
 - embed 2 youtube videos
 - display english or spanish depending on the version they choose.
 
 This page will have footer/bottom nav but will not have top navigation
