### ISSUE TITLE
!! Upload copy of test copy and location

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#747]
<img width="556" alt="Screen Shot 2021-04-07 at 11 35 40 AM" src="https://user-images.githubusercontent.com/64874011/113916897-637d2800-9795-11eb-9128-52aee6e36ab5.png">

7b  should say: 

"You will be asked to upload a copy of this test after this survey." 

They should only be asked to upload IF they answered yes. Can we place this comment only if they selected "Yes"?

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy - no we can not have ""You will be asked to upload a copy of this test after this survey." conditionally but we can change the text to say "If you answer "YES" you will be asked to upload a copy of this test after this survey."

**Comment by flylikeabirdfloatlikeabuoy** [comment]
In going through the flow and reading this again, I think we want to avoid folks saying "Prefer not to answer" or  "No" because they don't want to upload a file. 

Let's just remove the text entirely because we explain why we're asking for it later on. 
What do you think? 

Thanks,
