### ISSUE TITLE
Allow users toggle off/on Google analytics for privacy tracking

### ISSUE THREAD

**Issue by jay-hodgson** [Sage-Bionetworks/covidrecoverycorps#75]
(reported by Vanessa)

**Comment by mkellen** [comment]
Do we really need to do this? Seems like a pretty standard things most websites do

**Comment by jay-hodgson** [comment]
Not sure if we need to do this.  But if we do, then it looks like there's a way to do it:
https://developers.google.com/analytics/devguides/collection/gtagjs/user-opt-out

The complication is that it must be set before any calls to gtag()!  So we can't just set the window variable and refresh (since it would be cleared out).   I think this means that we would need to handle this ourselves by setting something that persists (in web storage or a cookie) and then refresh the page (don't call gtag() if set).

**Comment by conundrumgirl** [comment]
won't fix
