### ISSUE TITLE
!!! Did we remove question 9?

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#759]
Didn't see question 9 on the latest survey anymore in staging...wasn't sure if Wendy took it off or if this was an accident? 

<img width="318" alt="Screen Shot 2021-04-15 at 10 24 49 AM" src="https://user-images.githubusercontent.com/64874011/114912407-d1000880-9dd4-11eb-86b5-7f591c3e21c4.png">

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Current staging ends on 8c:

<img width="1449" alt="Screen Shot 2021-04-15 at 10 25 19 AM" src="https://user-images.githubusercontent.com/64874011/114912475-e37a4200-9dd4-11eb-86d8-255da9e401fa.png">

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy  - we only show second dose more Moderna or Pfizer
