### ISSUE TITLE
Selecting Survey Medical History

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#81]
When I select on Medical History Survey:

I get redirected to pregnancy question before asking about general medical history background first. 

Upon entry of all valid inputs, I get all these error statements.

![Screen Shot 2020-05-08 at 2 13 05 PM](https://user-images.githubusercontent.com/64874011/81449963-47f93f80-9136-11ea-8945-6e8572330cad.png)

**Comment by conundrumgirl** [comment]
this should not happen any more
