### ISSUE TITLE
URGENT: Survey 2 questions about ethnicity update

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#92]
Please make sure that: 
2. What is your ethnicity/ancestry? (check all that apply)

becomes a  check box style input  that allows for multiple selections rather only one (because people of multiple race)

![Screen Shot 2020-05-08 at 9 00 47 PM](https://user-images.githubusercontent.com/64874011/81463594-721b2380-916f-11ea-987d-536532047e02.png)

**Comment by conundrumgirl** [comment]
Lynn, this is exactly what it looks like on staging.
![image](https://user-images.githubusercontent.com/5190623/81488095-2a50d680-9219-11ea-92d2-e2ec6807ad28.png)
@flylikeabirdfloatlikeabuoy , can you please doublecheck and close this issue if it looks as it should

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-05-09 at 11 56 05 PM](https://user-images.githubusercontent.com/64874011/81492890-a7e40900-9250-11ea-93aa-4cfa64d546ba.png)

Thanks for the followup. Sorry from the google doc didn't look like the question was phrased as a checkbox.

 But the updates to it are:

+  Latino should be "Latinx"
+ Other should be: input text field for them to specify. 

Thanks

**Comment by conundrumgirl** [comment]
done
