### ISSUE TITLE
URGENT Survey 1: update Biological sex input fields

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#93]
Per Wendy's update: 

Change question 4. What was your biological sex assigned at birth to only be:

Female 
Male
Other

![Screen Shot 2020-05-08 at 9 58 33 PM](https://user-images.githubusercontent.com/64874011/81464480-118fe480-9177-11ea-8558-e4aa8a2d0b28.png)

**Comment by conundrumgirl** [comment]
fixed
